Added Societe Generale overview description to collateral pages.
makerdao/governance-manual pull request #133
Opened 2022-10-10 12:52 UTC by LongForWisdom

2022-10-11 14:34 UTC, patrick-j-govalpha requested changes

2022-10-11 14:34 UTC, patrick-j-govalpha commented on collateral/collateral-overview.md
> +Different blends of short-terms bonds from ultra-short (<1 year) to short (1-3 years) maturities. Investments done through BlackRock and Baillie Gifford. Mainly invested in US Treasuries but some exp
```suggestion
Different blends of short-term bonds from ultra-short (<1 year) to short (1-3 years) maturities. Investments done through BlackRock and Baillie Gifford. Mainly invested in US Treasuries but some exposure to corporate bonds.
```

2022-10-11 14:34 UTC, patrick-j-govalpha commented on collateral/collateral-overview.md
> +Different blends of short-terms bonds from ultra-short (<1 year) to short (1-3 years) maturities. Investments done through BlackRock and Baillie Gifford. Mainly invested in US Treasuries but some exp
Can you point to where the Blackrock and Baillie Gifford information is? Just tried ctrl+f on the socgen proposal threads and can't find those brokers listed.

2022-10-12 11:47 UTC, LongForWisdom commented on collateral/collateral-overview.md
> +Different blends of short-terms bonds from ultra-short (<1 year) to short (1-3 years) maturities. Investments done through BlackRock and Baillie Gifford. Mainly invested in US Treasuries but some exp
Nope, CES wrote it, not sure what source they're using.

2022-10-12 12:12 UTC, patrick-j-govalpha commented on collateral/collateral-overview.md
> +Different blends of short-terms bonds from ultra-short (<1 year) to short (1-3 years) maturities. Investments done through BlackRock and Baillie Gifford. Mainly invested in US Treasuries but some exp
Hmm. I'm suspicious that someone has mixed up SocGen and Monetalis. The SocGen application states:

"the OFH Tokens are characterized as covered bonds under French Law backed by home loans and benefiting from a statutory privilege, issued by Societe Generale SFH (SG SFH) a specialized credit institution with the status of Société de Financement de l’Habitat delivered by the Authorité de Contrôle Prudentiel (as further described below) in the form of security tokens in the Ethereum public blockchain."

which doesn't sounds like the description above

2022-10-12 13:11 UTC, LongForWisdom commented on collateral/collateral-overview.md
> +Different blends of short-terms bonds from ultra-short (<1 year) to short (1-3 years) maturities. Investments done through BlackRock and Baillie Gifford. Mainly invested in US Treasuries but some exp
You're correct, it's supposed to apply to Monetalis. My fault, I think, was reading discord chat wrong. Embarassing. We don't even have Monetalis onboard yet :/ Will update and can merge when Monetalis draws funds.

2022-10-13 20:14 UTC, patrick-j-govalpha approved these changes

2022-10-13 20:14 UTC, merged