Parameter formatting fixes
makerdao/governance-manual pull request #142
Opened 2022-10-11 13:38 UTC by LongForWisdom

Note, the summary.md has to change because gitbook takes page titles from that md file, rather than from the page md itself. 

Otherwise largely misc changes to improve formatting. Present on staging: https://longforwisdom.gitbook.io/new-collection/

2022-10-11 14:52 UTC, patrick-j-govalpha commented on parameter-index/debt-auction/param-bid-size.md
> +**Why decrease this parameter?**
As an aside are we better to make these subheadings?

so `### Why Increase this parameter` instead of `**Why Increase this parameter?**`

2022-10-12 13:26 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-size.md
> +**Why decrease this parameter?**
We could. I decided against it in the past as being a little too over the top. Maybe part of it was not wanting people to link to the part that supports their argument only.

2022-10-12 13:27 UTC, patrick-j-govalpha requested changes

2022-10-12 13:54 UTC, patrick-j-govalpha commented on parameter-index/debt-auction/param-bid-size.md
> +**Why decrease this parameter?**
It's not a massive issue, happy to leave it as is for now

2022-10-13 20:15 UTC, patrick-j-govalpha approved these changes

2022-10-13 20:15 UTC, merged