Maintenance batch - Overview + Structure
makerdao/governance-manual pull request #146
Opened 2022-10-12 14:30 UTC by LongForWisdom

Maintenance Pass for:
- protocol-status\acronyms.md - [Staging Link](https://longforwisdom.gitbook.io/new-collection/makerdao/overview/acronyms)
- core-units\core-unit-budget-flow.md - [Staging Link](https://longforwisdom.gitbook.io/new-collection/makerdao/overview/core-unit-budget-flow)
- protocol-status\protocol-and-dao-status.md - [Staging Link](https://longforwisdom.gitbook.io/new-collection/makerdao/overview/protocol-and-dao-status)
- core-units\core-units.md - [Staging Link](https://longforwisdom.gitbook.io/new-collection/makerdao/structure/core-units)
- governance\mips.md - [Staging Link](https://longforwisdom.gitbook.io/new-collection/makerdao/structure/mips)

2022-10-17 11:19 UTC, patrick-j-govalpha requested changes

2022-10-17 11:19 UTC, patrick-j-govalpha commented on core-units/core-unit-budget-flow.md
> +{% embed url="https://miro.com/app/board/uXjVOwW_Q3M=?embedAutoplay=true&pres=1&frameId=3458764526661727988" %}
Who maintains this?

Still has LFW as a signer on the GovAlpha budget flow, haven't looked at the rest of the CUs

2022-10-17 11:19 UTC, patrick-j-govalpha commented on core-units/core-units.md
> +* *Facilitator* subproposals (see [MIP41](https://mips.makerdao.com/mips/details/MIP41)) establish individuals as official points of contact and parties responsible for the Core Unit fulfilling its m
Think we should add something that explains the difference between facilitator and gov facilitator? might help the academy team too...

2022-10-17 11:19 UTC, patrick-j-govalpha commented on protocol-status/acronyms.md
> +* `Burban`: [Strategic Happiness Core Unit (SH-001)](https://mips.makerdao.com/mips/details/MIP39c2SP11)
```suggestion
* `Burban/SH`: [Strategic Happiness Core Unit (SH-001)](https://mips.makerdao.com/mips/details/MIP39c2SP11)

```

2022-10-17 11:19 UTC, patrick-j-govalpha commented on protocol-status/acronyms.md
> +### Real World Assets
Monetalis?

2022-10-20 14:23 UTC, LongForWisdom commented on core-units/core-unit-budget-flow.md
> +{% embed url="https://miro.com/app/board/uXjVOwW_Q3M=?embedAutoplay=true&pres=1&frameId=3458764526661727988" %}
Ah, that's maintained by SES, Retro gave me access, but I'd rather not commit to maintenance on it.

2022-10-20 14:25 UTC, LongForWisdom commented on core-units/core-units.md
> +* *Facilitator* subproposals (see [MIP41](https://mips.makerdao.com/mips/details/MIP41)) establish individuals as official points of contact and parties responsible for the Core Unit fulfilling its m
I feel like that might be out of scope for this page? Like, it's about core units generally rather than the specifics. Maybe we need a page on governance roles or something.

2022-10-20 14:26 UTC, LongForWisdom commented on protocol-status/acronyms.md
> +### Real World Assets
Doesn't really have a abbreviation that I'm aware of? Happy to add one if I've missed it.

2022-10-25 02:25 UTC, Gala-G reviewed
It looks great. I commented on a few things.
Thank you, Long

2022-10-25 02:25 UTC, Gala-G commented on core-units/core-units.md
> +Each active Core Unit consists of at least three active subproposals (i.e., subproposals that have not been superseded by other subproposals):
Since you made out a list of a previous sentence, I would rewrite it as follows:

Each active Core Unit consists of at least three active subproposals (i.e., subproposals that have not been superseded by other subproposals):
* A *mandate* subproposal (see [MIP39](https://mips.makerdao.com/mips/details/MIP39)) that lays out the objectives and directions that a given Core Unit is responsible for fulfilling. 
* A *budget* subproposal (see [MIP40](https://mips.makerdao.com/mips/details/MIP40)), to request the funding to meet these objectives.
* A *Facilitator* subproposal (see [MIP41](https://mips.makerdao.com/mips/details/MIP41)) that establishes individuals as official points of contact and parties responsible for the Core Unit fulfilling its mandate.

2022-10-25 02:25 UTC, Gala-G commented on core-units/core-units.md
> +- **Breakdown**: List of expenses by type, disclose full-time equivalent headcount.
"discloses"

2022-10-25 02:25 UTC, Gala-G commented on core-units/core-units.md
> +- **Contingency Planning**: Describe how the core unit will cease operations in the event of offboarding.
"Describes"

2022-10-25 02:25 UTC, Gala-G commented on governance/mips.md
> +A Maker Improvement Proposal (MIP) is a document that regulates and defines the behavior of Maker Governance, MakerDAO or the Maker Protocol. They are standardized documents voted upon by Maker Gover
"A Maker Improvement Proposal (MIP) is a document that regulates and defines the behavior of Maker Governance, MakerDAO, or the Maker Protocol."

add a comma (,) after "MakerDAO"

2022-10-25 15:56 UTC, LongForWisdom commented on core-units/core-units.md
> +Each active Core Unit consists of at least three active subproposals (i.e., subproposals that have not been superseded by other subproposals):
Agree, will do.

2022-10-25 15:58 UTC, LongForWisdom commented on core-units/core-units.md
> +- **Contingency Planning**: Describe how the core unit will cease operations in the event of offboarding.
Agree, and I've updated the other lines to use the same sort of sentence structure.

2022-10-25 15:58 UTC, LongForWisdom commented on core-units/core-units.md
> +- **Breakdown**: List of expenses by type, disclose full-time equivalent headcount.
Agree, and I've updated the other lines to use the same sort of sentence structure.

2022-10-25 16:02 UTC, LongForWisdom commented on core-units/core-unit-budget-flow.md
> +{% embed url="https://miro.com/app/board/uXjVOwW_Q3M=?embedAutoplay=true&pres=1&frameId=3458764526661727988" %}
I'll chase up.

2022-10-26 16:27 UTC, patrick-j-govalpha approved these changes
LGTM - merging

2022-10-26 16:28 UTC, merged