DRAFT: Review for on-chain-governance page
makerdao/governance-manual pull request #148
Opened 2022-10-25 17:23 UTC by LongForWisdom

2022-10-25 17:45 UTC, blimpa requested changes

2022-10-25 17:45 UTC, blimpa commented on governance/on-chain-governance.md
>  Anyone can create an on-chain Executive Vote using the MakerDAO governance contracts, however, there is no non-technical UI available to do this. Users can create proposals, also known as [slates](ht
```suggestion
Anyone can create an on-chain Executive Vote using the MakerDAO governance contracts; however, there is no non-technical UI available to do this. Users can create proposals, also known as [slates](https://docs.makerdao.com/smart-contract-modules/governance-module/chief-detailed-documentation), through this [experimental portal](https://chief.makerdao.com/), or by interacting directly with the smart contracts.
```

2022-10-26 17:18 UTC, patrick-j-govalpha requested changes

2022-10-26 17:26 UTC, LongForWisdom commented on governance/on-chain-governance.md
>  ### Executive Votes
Initially agreed, but am now less sure. Part of the reason for having the page title be 'on-chain governance' versus 'off-chain governance' was that people that don't know how governance works at Maker know better what to click on. Like, if you know nothing and want to know what governance happens on-chain right now its easy to find. Will be less easy if I split this into two pages titled on-chain polls and executive votes.

2022-10-31 18:54 UTC, merged