Vault Risk Parameters Scheduled Maintenance
makerdao/governance-manual pull request #178
Opened 2022-11-07 17:20 UTC by blimpa

- Liquidation Penalty
- Liquidation Ratio

2022-11-07 18:05 UTC, LongForWisdom requested changes
Thanks, @blimpa, see comments!

2022-11-07 18:05 UTC, LongForWisdom commented on parameter-index/vault-risk/param-liquidation-penalty.md
> +>**Technical Docs:** [Liquidation 2.0 Module](https://docs.makerdao.com/smart-contract-modules/dog-and-clipper-detailed-documentation)
I think we've just used 'Liquidations 2.0' elsewhere?

2022-11-07 18:05 UTC, LongForWisdom commented on parameter-index/vault-risk/param-liquidation-ratio.md
> +Alternatively, a Liquidation Ratio might be decreased to increment the competitiveness (in terms of capital efficiency) of a vault type when compared to the wider market.
Increment doesn't make sense in this context. Increment means more 'increase by a discrete amount' usually one. Competitiveness can't really be described in discrete terms, so increase is the better fit, imo.

2022-11-07 18:10 UTC, blimpa commented on parameter-index/vault-risk/param-liquidation-ratio.md
> +Alternatively, a Liquidation Ratio might be decreased to increment the competitiveness (in terms of capital efficiency) of a vault type when compared to the wider market.
Oh, I don't think I was aware of the difference. Cool. I just wanted to avoid the cacophony

2022-11-09 18:23 UTC, LongForWisdom approved these changes

2022-11-09 18:24 UTC, merged