DONE: Review pass collateral auction drawdown and duration.
makerdao/governance-manual pull request #179
Opened 2022-11-07 17:49 UTC by LongForWisdom

Staging Links:
[Collateral Auction Drawdown](https://longforwisdom.gitbook.io/new-collection/parameter-index/collateral-auction/param-max-auction-drawdown)
[Collateral Auction Duration](https://longforwisdom.gitbook.io/new-collection/parameter-index/collateral-auction/param-max-auction-duration)

2022-11-07 18:36 UTC, blimpa commented on parameter-index/collateral-auction/param-max-auction-duration.md
> +During an [Emergency Shutdown](https://docs.makerdao.com/smart-contract-modules/shutdown), new auctions are halted, but the Three-Stage Liquidations Circuit Breaker determines if ongoing auctions can
Four-stage, I think

2022-11-23 17:49 UTC, blimpa requested changes

2022-11-23 17:49 UTC, blimpa commented on parameter-index/collateral-auction/param-max-auction-drawdown.md
>  >**Alias:**
```suggestion
>**Alias:**  Max Auction Drawdown
```

2022-11-23 17:49 UTC, blimpa commented on parameter-index/collateral-auction/param-max-auction-drawdown.md
> +Auction resets can only take place when either the Maximum Auction Drawdown parameter or the Maximum Auction Duration parameter are exceeded.
Maybe let's just keep using "max"?

2022-11-23 17:49 UTC, blimpa commented on parameter-index/collateral-auction/param-max-auction-duration.md
> +The Maximum Auction Duration parameter overlaps with the [Maximum Auction Drawdown](param-max-auction-drawdown.md) parameter in that an auction will need to be reset once either maximum is exceeded.
Maybe let's just keep using "max"?

2022-11-23 17:49 UTC, blimpa commented on parameter-index/collateral-auction/param-max-auction-duration.md
> +If auctions are too short there is a risk of liquidations not ending profitably before a reset is required. This may be negative depending on the settings for the [Flat Kick Incentive](param-flat-kic
```suggestion
If auctions are too short, there is a risk of liquidations not ending profitably before a reset is required. This may be negative depending on the settings for the [Flat Kick Incentive](param-flat-kick-incentive.md) and the [Proportional Kick Incentive](param-proportional-kick-incentive.md) because these incentives are paid to keepers at each reset.
```

2022-11-23 17:49 UTC, blimpa commented on parameter-index/collateral-auction/param-max-auction-duration.md
> +During an [Emergency Shutdown](https://docs.makerdao.com/smart-contract-modules/shutdown), new auctions are halted, but the [Four-Stage Liquidations Circuit Breaker](https://docs.makerdao.com/smart-c
```suggestion
During an [Emergency Shutdown](https://docs.makerdao.com/smart-contract-modules/shutdown), new auctions are halted, but the [Four-Stage Liquidations Circuit Breaker](https://docs.makerdao.com/smart-contract-modules/dog-and-clipper-detailed-documentation#four-stage-liquidation-circuit-breaker) determines if ongoing auctions can be reset or not. If only one additional level of the circuit breaker is triggered, the Maximum Auction Duration will still be used to check eligibility for auction reset, but under the most severe level of the Liquidations Circut breaker no resets can be performed, thus limiting the effectiveness of the parameter.
```

2022-11-23 17:49 UTC, blimpa commented on parameter-index/collateral-auction/param-max-auction-duration.md
>  The trade-offs to this parameter are heavily tied to the Auction Price Function parameter, as the shape of the curve may heavily affect the desired auction length.
Are we omitting "parameter" for this one?

2022-11-23 17:49 UTC, blimpa commented on parameter-index/collateral-auction/param-max-auction-drawdown.md
> +Maximum Auction Drawdown is based on the starting auction price (`top`), which is equal to the OSM price multiplied by the Auction Price Multiplier (`buf`).
Crosslink `buf`?

2022-11-23 17:49 UTC, blimpa commented on parameter-index/collateral-auction/param-max-auction-drawdown.md
>  If a collateral auction starts at a collateral price of $100, and the Maximum Auction Drawdown is set to 70%, the auction will be reset if the auction collateral price reaches $30.
Maybe introduce this explicitely as an example?

2022-11-23 17:49 UTC, blimpa commented on parameter-index/collateral-auction/param-max-auction-duration.md
> +The Maximum Auction Duration parameter overlaps with the [Maximum Auction Drawdown](param-max-auction-drawdown.md) parameter in that an auction will need to be reset once either maximum is exceeded.
(There are more instances of this, btw)

2022-11-23 18:41 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-max-auction-drawdown.md
>  If a collateral auction starts at a collateral price of $100, and the Maximum Auction Drawdown is set to 70%, the auction will be reset if the auction collateral price reaches $30.
As a general rule, I try not to unless it's very complicated. This is a simple one, so didn't bother.

2022-11-23 18:43 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-max-auction-drawdown.md
> +Auction resets can only take place when either the Maximum Auction Drawdown parameter or the Maximum Auction Duration parameter are exceeded.
Yeah, might be a good idea.

2022-11-23 18:44 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-max-auction-duration.md
>  The trade-offs to this parameter are heavily tied to the Auction Price Function parameter, as the shape of the curve may heavily affect the desired auction length.
In what way?

2022-11-25 15:31 UTC, blimpa commented on parameter-index/collateral-auction/param-max-auction-duration.md
>  The trade-offs to this parameter are heavily tied to the Auction Price Function parameter, as the shape of the curve may heavily affect the desired auction length.
Disregard. I think I misread something

2022-11-25 15:45 UTC, merged