MOM review
makerdao/governance-manual pull request #184
Opened 2022-11-07 18:09 UTC by Gala-G

update

2022-11-07 18:39 UTC, Gala-G commented
Staging links:
https://longforwisdom.gitbook.io/new-collection/parameter-index/collateral-auction/param-auction-price-function
https://longforwisdom.gitbook.io/new-collection/parameter-index/collateral-auction/param-auction-price-multiplier

2022-11-07 18:39 UTC, blimpa commented on parameter-index/collateral-auction/param-auction-price-function.md
> +A value expressed in seconds which controls how long it takes for the price of a Linear Decrease auction to reach zero. This controls the rate of fall in the price of the collateral being auctioned.
So is tau a function or a parameter? Sounds like it's a parameter here, but we just said it's a function

2022-11-09 16:46 UTC, LongForWisdom requested changes
Thanks Gala, see comments.

2022-11-09 16:46 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-auction-price-function.md
> +>**Containing Contract:** `MCD_CLIP_$ILK`
I would also change the key here from 'Containing Contract' -> 'Containing Contracts'. Uniquely (I think?) among our parameters, there are multiple contacts (one per ilk) as opposed to a single contract with a mapping of ilks->parameters.

2022-11-09 16:46 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-auction-price-function.md
> +In an auction utilizing a Linear Decrease Auction Price Function, the auction will start at a price defined by the Auction Price Multiplier. The price will decrease linearly over time until it reache
`tau` is a parameter here, not a function.

2022-11-09 16:46 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-auction-price-function.md
> +A value expressed in seconds which controls how long it takes for the price of a Linear Decrease auction to reach zero. This controls the rate of fall in the price of the collateral being auctioned.
Hah, good catch also Pablo. Yes, I believe it's a parameter.

2022-11-09 16:46 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-auction-price-function.md
> +The Linear Decrease function is also bounded by the [Maximum Auction Duration parameter](param-max-auction-duration.md). This can be used to set a lower bound on the price accepted by the Maker Proto
Minor thing, but probably just hyperlink the parameter name. So [Maximum Auction Duration parameter]. -> [Maximum Auction Duration] parameter.

2022-11-09 16:46 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-auction-price-function.md
> +Adjusting an Auction Price Function parameter is a manual process that requires an executive vote. Changes to an Auction Price Function are subject to the [GSM Pause Delay](param-gsm-pause-delay.md).
Check this link works on the staging site :)

2022-11-09 16:46 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-auction-price-multiplier.md
> +>**Containing Contract:** `MCD_CLIP_$ILK`
Again, imo Contract -> Contracts

2022-11-09 16:46 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-auction-price-multiplier.md
> +The primary purpose of the Auction Price Multiplier is so that, when falling price collateral auctions begin, the Maker Protocol does not begin the auction lower than the current market price in the
Feels like this should be reworded some? Dunno, the first sentence sounds pretty awkward.

2022-11-09 16:46 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-auction-price-multiplier.md
> +Adjusting an Auction Price Multiplier parameter for a specific vault type is a manual process that requires an executive vote. Changes to Auction Price Multiplier parameters are subject to the [GSM P
Check this link too.

2022-11-09 16:46 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-auction-price-multiplier.md
> +An Auction Price Multiplier parameter might be decreased for a specific vault type if in the general case auctions were being regularly reset due to the price reaching the [Max Auction Drawdown](max-
And check this one.

2022-11-09 16:46 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-auction-price-function.md
> +>Page last reviewed: 11-07-2022
YYYY-MM-DD

2022-11-09 16:46 UTC, LongForWisdom commented on parameter-index/collateral-auction/param-auction-price-multiplier.md
> +>Page last reviewed: 11-07-2022
YYYY-MM-DD

2022-11-14 16:09 UTC, LongForWisdom approved these changes

2022-11-14 17:12 UTC, merged