Debt ceiling doc
makerdao/governance-manual pull request #185
Opened 2022-11-07 18:12 UTC by astronautthis

Staging branch link: https://github.com/makerdao/governance-manual/pull/182

2022-11-07 18:43 UTC, blimpa commented on parameter-index/vault-risk/param-debt-ceiling.md
>  Additionally, there is a Global Debt Ceiling parameter that is not covered in this entry. For a user to mint DAI from their vault, there must be space available in both the vault type's Debt Ceiling
I think we should link to the Global Debt Ceiling MOM page here

2022-11-07 18:43 UTC, blimpa commented on parameter-index/vault-risk/param-debt-ceiling.md
>  Increasing the Debt Ceiling parameter for a vault type allows more DAI to be minted using that vault type. In most cases, this is positive as Maker Governance will almost always want more DAI to exis
```suggestion
Increasing the Debt Ceiling parameter for a vault type allows more DAI to be minted using that vault type. In most cases, this is positive as Maker Governance will almost always want more DAI to exist as long as that the price peg to $1 can be maintained.
```

2022-11-09 16:36 UTC, LongForWisdom requested changes
Thanks Astro, see comments.

2022-11-09 16:36 UTC, LongForWisdom commented on parameter-index/vault-risk/param-debt-ceiling.md
> +Having a large amount of open space known as `gap` between the Debt Ceiling for a vault type and the current amount of DAI minted using that vault type represents a risk. In the event of a significan
I wouldn't change this in this way here. we're not explicitly referring to the DCIAM parameter when we talk about the open space here. We're talking about the actual difference between the debt used, and debt available, versus the Target Available Debt parameter, which is known as `gap` in the DCIAM.

2022-11-09 16:36 UTC, LongForWisdom commented on parameter-index/vault-risk/param-debt-ceiling.md
> +Leaving a large `gap` in the Debt Ceiling for a vault type also means that the DAI supply can change rapidly in a way that may harm the DAI price peg.
I wouldn't change this in this way here. we're not explicitly referring to the DCIAM parameter when we talk about the open space here. We're talking about the actual difference between the debt used, and debt available, versus the Target Available Debt parameter, which is known as `gap` in the DCIAM.

2022-11-09 16:36 UTC, LongForWisdom commented on parameter-index/vault-risk/param-debt-ceiling.md
> +Adjusting the Debt Ceiling parameter for a specific vault type can be done via an [Executive Vote](../../governance/on-chain-governance.md). Changes to Debt Ceiling parameters done via an Executive V
I don't think it's necessary to link to Executive Vote here, we haven't in other docs, and I feel like the assumption is that if you're diving this deep, you _probably_ know what an executive is. 

I would also stick to the phrasing used elsewhere where possible/easier. Something like:

"Adjustment to the Debt Ceiling parameter for a specific vault type may be made using a manual process that requires an executive vote. Alternatively..."

2022-11-09 16:36 UTC, LongForWisdom commented on parameter-index/vault-risk/param-debt-ceiling.md
> +Some vaults use a [Debt Ceiling Instant Access Module (DC-IAM)](../../module-index/module-dciam.md) that can change the Debt Ceiling parameter without an Executive Vote.
There is only one module, so it would be 'the' rather than 'a'. I would also be more specific about how it works. 'That can change the debt ceiling parameter according to pre-set parameters without requiring an Executive Vote.

2022-11-09 16:36 UTC, LongForWisdom commented on parameter-index/vault-risk/param-debt-ceiling.md
> +The parameter can also be used to encourage diversification between vault types that are based on similar assets. For example, decreasing the Debt Ceiling on rETH could be used to shift staked ETH us
Imo stick with vaults that are in use as examples? In this case, maybe use the PSM's? Or ETH and stETH?

2022-11-09 16:36 UTC, LongForWisdom commented on parameter-index/vault-risk/param-debt-ceiling.md
> +The parameter can also be used to encourage diversification between vault types that are based on similar assets. For example, decreasing the Debt Ceiling on rETH could be used to shift staked ETH us
Also remember these are _vaults_ and not _collateral_, you should use the ilk names, rather than the collateral  ticker.

2022-11-09 16:36 UTC, LongForWisdom commented on parameter-index/vault-risk/param-rwa-agreement.md
>  >**Containing Contract:** `RwaLiquidationOracle`
Use the chainlog version: MIP21_LIQUIDATION_ORACLE

2022-11-09 17:51 UTC, astronautthis commented
@LongForWisdom incorporated your comments, let me know if it's all good and I'll change the title to DONE :)

2022-11-14 16:06 UTC, LongForWisdom approved these changes

2022-11-14 17:08 UTC, merged