Module index maintenance
makerdao/governance-manual pull request #188
Opened 2022-11-07 18:39 UTC by TheExistence

2022-11-07 20:30 UTC, blimpa commented on module-index/module-dciam.md
> +The rules defined in the DC-IAM smart-contract encourage an amount of 'open space' between the current debt usage and the Debt Ceiling of a vault type. The DC-IAM holds three parameters that can be s
Remove slashes
```suggestion
The rules defined in the DC-IAM smart-contract encourage an amount of 'open space' between the current debt usage and the Debt Ceiling of a vault type. The DC-IAM holds three parameters that can be set by governance for each vault type (such as ETH-A.).
```

2022-11-07 20:30 UTC, blimpa commented on module-index/module-dciam.md
>  ### Maximum Debt Ceiling \(`line`\)
```suggestion
### Maximum Debt Ceiling (`line`)
```

2022-11-07 20:30 UTC, blimpa commented on module-index/module-dciam.md
>  ### Target Available Debt \(`gap`\)
```suggestion
### Target Available Debt (`gap`)
```

2022-11-09 17:46 UTC, LongForWisdom requested changes
More changes needed in token streaming as well, but I can't comment on them directly because file is mostly unchanged.

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
Update preamble and generally run through checklist here: https://docs.google.com/spreadsheets/d/1WvFGQJEP0fjY0pUhwU-RVq04DUYGk64EvH1LNNgopjs/edit#gid=1133002554

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
Also we should try to find some technical docs.

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
> +The Debt Ceiling parameter for the DAI Direct Deposit Module is substantially identical to the [Debt Ceiling](https://manual.makerdao.com/parameter-index/vault-risk/param-debt-ceiling) parameter for
Use relative links, rather than absolute links, please.

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
> +It is possible to deactivate the Aave D3M by setting the Target Borrow Rate to 0. Note that while setting the Target Borrow Rate to 0 might intuitively suggest that the Aave D3M will utilize its full
'using a `DIRECT_MOM` -> using the `DIRECT_MOM` contract

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
>  Recursive lending is common on lending protocols due to yield farming. This is where a user deposits DAI as collateral, borrows DAI from the protocol, and deposits the borrowed DAI back into the prot
So, there's a lot of text above here that didn't change. Are you confident no updates are needed there?

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-dciam.md
> +The Debt Ceiling Instant Access Module allows any user to adjust the [Debt Ceiling](https://manual.makerdao.com/parameter-index/vault-risk/param-debt-ceiling) of a supported vault type according to r
Relative links, please

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-dciam.md
Please update preamble according to checklist: https://docs.google.com/spreadsheets/d/1WvFGQJEP0fjY0pUhwU-RVq04DUYGk64EvH1LNNgopjs/edit#gid=1133002554

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-dciam.md
>  For example, if the ETH-A Debt Ceiling is currently 100 DAI, and 90 DAI is drawn as debt, the DC-IAM could be used to increase the ETH-A debt ceiling to 110 DAI, enforcing a 20 DAI gap between the us
I think the second usage of 'ETH-A Debt Ceiling' is incorrect here? It reads like it should be debt usage.

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-dciam.md
> +These parameters are `line`, `gap`, and `ttl`, and their effect is described in detail in the Key Parameters section.
What's the rationale for moving this?

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-dciam.md
> +The Maximum Debt Ceiling refers to the maximum value for Debt Ceiling that the DC-IAM will allow in the given vault type. This parameter is also named `line` within the smart contract. When using the
Relative links, please.

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-token-streaming.md
> +6. After 12 months, the contributor may apply for the remainder of the MKR.
'may apply for' implies incorrect things. It's not an application, the user can directly claim the funds from the smart contract.

2022-11-09 17:46 UTC, LongForWisdom commented on module-index/module-token-streaming.md
>  3. Prior to 6 months passing, the contributor will not be able to redeem any MKR from the vesting contract.
Also update preamble.

2022-11-11 13:11 UTC, TheExistence commented on module-index/module-dai-direct-deposit.md
I updated the contract name with `MCD_JOIN_DIRECT_AAVEV2_DAI` and in scope i put System. Not sure if it's ok. Also, coudn't find tech docs on D3M. Do you know where i can look for it?

2022-11-11 15:14 UTC, TheExistence commented on module-index/module-dciam.md
>  For example, if the ETH-A Debt Ceiling is currently 100 DAI, and 90 DAI is drawn as debt, the DC-IAM could be used to increase the ETH-A debt ceiling to 110 DAI, enforcing a 20 DAI gap between the us
Changed reduce for set

2022-11-11 15:20 UTC, TheExistence commented on module-index/module-dciam.md
>  For example, if the ETH-A Debt Ceiling is currently 100 DAI, and 90 DAI is drawn as debt, the DC-IAM could be used to increase the ETH-A debt ceiling to 110 DAI, enforcing a 20 DAI gap between the us
I changed the word reduce to the word set, do you think it looks better now?

2022-11-11 15:20 UTC, TheExistence commented on module-index/module-dciam.md
> +These parameters are `line`, `gap`, and `ttl`, and their effect is described in detail in the Key Parameters section.
My bad, here I wanted to summarize the text a bit.

2022-11-11 23:11 UTC, TheExistence commented on module-index/module-dciam.md
>    * **YFI-A**
I was planning to update the active vault list from here https://tracker-vaults.makerdao.network/
It is not clear to me where I can get the hexadecimal codes for all active vault types

2022-11-16 17:33 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
See new comment. As for technical docs, not sure. Maybe ask PE?

2022-11-16 17:35 UTC, LongForWisdom commented on module-index/module-dciam.md
>    * **YFI-A**
I think the hexcodes are just the ilk-name converted to hex format. You should be able to check against the ones that are already here. The best way to find the list of active vaults is probably to look on Makerburn and get everything with DC > 0.

2022-11-16 17:46 UTC, LongForWisdom requested changes
See new comments

2022-11-16 17:46 UTC, LongForWisdom commented on module-index/module-token-streaming.md
> ->**Contract Names:** DSSVestMintable, DssVestSuckable, DssVestTransferrable
Use MCD_VEST_DAI rather than MCD_VEST_DAI_LEGACY

2022-11-16 17:46 UTC, LongForWisdom commented on module-index/module-token-streaming.md
> -* Minted DAI - One version of the contract (DssVestSuckable) supports streaming purpose-minted DAI tokens.
Use MCD_VEST_DAI rather than MCD_VEST_DAI_LEGACY

2022-11-16 17:46 UTC, LongForWisdom commented on module-index/module-token-streaming.md
> -MCD_VEST_DAI - To get DAI minted from the Maker Protocol.
It should be MCD_VEST_DAI. Legacy version just exists because they changed it at some point.

2022-11-16 17:47 UTC, LongForWisdom commented on module-index/module-dciam.md
> +These parameters are `line`, `gap`, and `ttl`, and their effect is described in detail in the Key Parameters section.
Cool, I think it makes more sense as it was originally, otherwise you're separating the detail on the parameters with the example.

2022-11-17 22:22 UTC, TheExistence commented on module-index/module-dai-direct-deposit.md
>  Recursive lending is common on lending protocols due to yield farming. This is where a user deposits DAI as collateral, borrows DAI from the protocol, and deposits the borrowed DAI back into the prot
As far as I know, there have been no changes in this regard

2022-11-18 15:43 UTC, LongForWisdom commented
I think updating the list of ilk hexcodes is the only outstanding item.

2022-11-18 16:43 UTC, TheExistence commented
List updated :)

2022-11-21 17:47 UTC, LongForWisdom requested changes
On second thoughts, we should just take the list out. Maintenance is going to be too much of a pain.

2022-11-21 17:47 UTC, LongForWisdom commented on module-index/module-dciam.md
> +  * **PSM-USDC-A**
I think these were previously organized alphabetically? Might be worth keeping that, otherwise, they should probably be divided into sections.

2022-11-21 17:47 UTC, LongForWisdom commented on module-index/module-dciam.md
> +  * **PSM-USDC-A**
Are you sure all of these have the DC-IAM active on them? I'm not sure if Teleport does? When I referred to the list of active vaults previously, that was mainly meant to be a starting point, not that every vault with a positive debt ceiling also uses the DC-IAM.

2022-11-21 17:47 UTC, LongForWisdom commented on module-index/module-dciam.md
> +  * **PSM-USDC-A**
Honestly, we should just remove this list, it's going to be a nightmare to keep up to date, and we provide instructions on how to generate it anyway.

2022-11-22 14:36 UTC, TheExistence commented on module-index/module-dciam.md
> +  * **PSM-USDC-A**
Ok, got it. List removed

2022-11-23 17:32 UTC, LongForWisdom approved these changes

2022-11-23 17:32 UTC, merged