FOR REVIEW - Debt Auction Params scheduled maintenance
makerdao/governance-manual pull request #196
Opened 2022-11-09 18:45 UTC by blimpa

Staging links:
- [Flop Bid Duration](https://longforwisdom.gitbook.io/new-collection/parameter-index/debt-auction/param-bid-duration-flop)
- [Debt Auction Delay](https://longforwisdom.gitbook.io/new-collection/parameter-index/debt-auction/param-debt-auction-delay)
- [Initial Lot Size](https://longforwisdom.gitbook.io/new-collection/parameter-index/debt-auction/param-initial-lot-size)

2022-11-14 17:51 UTC, LongForWisdom requested changes

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-duration-flop.md
> +>**Containing Contract:** `MCD.FLOP`
MCD_FLOP

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-duration-flop.md
> +The Debt Auction (Flop) Bid Duration parameter (`ttl`) allows governance to control how soon after a successful bid a Debt Auction will end. Further bids reset this timer, extending the auction. A de
We should change all references to the parameter to 'Debt Auction Bid Duration' as opposed to Flop Bid Duration, Bid Duration (Flop), etc

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-duration-flop.md
> +A Flop Bid Duration that is small means that Keepers take less risk that the market will move while the auction is in progress. Since the risk is lower, keepers can submit more aggressive bids which
"A Flop Bid Duration that is small" - You rarely see this construction in native english, always tends to be 'A small thing' versus 'A thing that is small'.

"However, if the Flop Bid Duration is too small, there may not be enough time for keepers to organize funds and participate in such auctions" - Add... 'before they conclude' ?

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-duration-flop.md
>  ### Example
Is it even worth having an example here? I feel like min(x, y) isn't too complicated of a concept to communicate.

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-duration-flop.md
> +_Historic Note: A similar auction system was initially used for collateral auctions as well; it was replaced by a dutch auction system._
Probably not worth using the 'Historic Note' thing here, imo.

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-duration-flop.md
> +The Debt Auction (Flop) Bid Duration parameter (`ttl`) allows governance to control how soon after a successful bid a Debt Auction will end. Further bids reset this timer, extending the auction. A de
Crosslink on 'Flop Duration'?

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-duration-flop.md
> +Flop Bid Duration is always upper-bounded by the total auction duration. If it is set higher than the total auction duration, then it will have no effect.
Crosslink here as well?

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-debt-auction-delay.md
> +```text
Why \```text here rather than \``` ?

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-debt-auction-delay.md
> +The Debt Auction Delay exists to provide time for Keepers to bid on liquidated vaults via Collateral Auctions. If the Debt Auction Delay is set to zero, all liquidations will proceed instantly to Deb
```suggestion
The Debt Auction Delay exists to provide time for Keepers to bid on liquidated vaults via Collateral Auctions. If the Debt Auction Delay is set to zero, each liquidation would instantly trigger a Debt Auction, as well as a Collateral Auction, which would mint unnecessary amounts of MKR.
```

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-debt-auction-delay.md
>  Debt Auction Delay should be increased if the Max Auction Duration of Collateral auctions is increased to prevent unnecessary Debt Auctions. It might also be increased if a large number of Debt Aucti
crosslink?

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-debt-auction-delay.md
> +The Debt Auction Delay might be decreased if it is taking too long for Debt Auctions to commence, leaving the system undercollateralized for longer than acceptable, which could impact Dai users and u
I think I prefer the previous wording? I don't feel strongly about it though.

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-initial-lot-size.md
> +Debt Auctions are used to recapitalize the system by minting and auctioning off MKR for a fixed amount of DAI. In this process, keepers bid on how little MKR they are willing to accept for the fixed
So I know we talked about doing it later. But Dai and DAI in the same paragraph should be fixed?

2022-11-14 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-initial-lot-size.md
> +This parameter should be tuned in conjunction with the Debt Auction Lot Size Increase (`pad`) parameter, which has similar consequences when increased or decreased as the Debt Auction Initial Lot Siz
Crosslink?

2022-11-14 21:25 UTC, blimpa commented on parameter-index/debt-auction/param-bid-duration-flop.md
> +The Debt Auction (Flop) Bid Duration parameter (`ttl`) allows governance to control how soon after a successful bid a Debt Auction will end. Further bids reset this timer, extending the auction. A de
> We should change all references to the parameter to 'Debt Auction Bid Duration' as opposed to Flop Bid Duration, Bid Duration (Flop), etc

Hah. Yeah, was pretty sure mine wasn't the optimal solution

2022-11-14 21:36 UTC, blimpa commented on parameter-index/debt-auction/param-debt-auction-delay.md
> +The Debt Auction Delay might be decreased if it is taking too long for Debt Auctions to commence, leaving the system undercollateralized for longer than acceptable, which could impact Dai users and u
Agree tbh

2022-11-16 15:46 UTC, LongForWisdom requested changes
See further comments

2022-11-16 15:46 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-duration-flop.md
> +The Debt Auction Bid Duration parameter (`ttl`) allows governance to control how soon after a successful bid a Debt Auction will end. Further bids reset this timer, extending the auction. A debt auct
I think as a general rule, don't include the word 'parameter' in the crosslinks.

2022-11-16 15:46 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-duration-flop.md
>  Adjusting the Flop Bid Duration parameter is a manual process that requires an executive vote. Changes to the Flop Bid Duration are subject to the [GSM Pause Delay](../core/param-gsm-pause-delay.md).
Should change as well? Maybe find-replace 'Flop Bid Duration'?

2022-11-16 15:46 UTC, LongForWisdom commented on parameter-index/debt-auction/param-initial-lot-size.md
> +>Page last reviewed: 2022-14-09
Dates are wrong here? Not sure what went wrong, but should be YYYY-MM-DD, and November is month 11 rather than month 09.

2022-11-16 17:51 UTC, LongForWisdom commented on parameter-index/debt-auction/param-initial-lot-size.md
> +A lower amount of MKR than the initial lot size may be bid by auction participants. If there are no bids by the time the auction reaches its end, the Debt Auction Initial Lot Size will be increased w
```suggestion
A lower amount of MKR than the initial lot size may be bid by auction participants. If there are no bids by the time the auction reaches its end, the Debt Auction Initial Lot Size will be increased when the auction is restarted. This increase is determined by the Debt Auction Lot Size Increase parameter (`pad`).
```

2022-11-16 17:51 UTC, LongForWisdom requested changes
One minor fix

2022-11-18 16:53 UTC, LongForWisdom approved these changes

2022-11-18 16:53 UTC, merged