TO REVIEW: Debt Auction Params scheduled maintenance
makerdao/governance-manual pull request #209
Opened 2022-11-16 18:00 UTC by blimpa

Staging links:
- [Bid size](https://longforwisdom.gitbook.io/new-collection/parameter-index/debt-auction/param-bid-size)
- [Lot size increase](https://longforwisdom.gitbook.io/new-collection/parameter-index/debt-auction/param-lot-size-increase)
- [Min bid decrease](https://longforwisdom.gitbook.io/new-collection/parameter-index/debt-auction/param-min-bid-decrease-flop)

2022-11-16 18:16 UTC, LongForWisdom requested changes

2022-11-16 18:16 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-size.md
> +A small Debt Auction Bid Size would result in an auction being triggered more quickly when the protocol is undercollateralized. If the protocol is quickly recollateralized, this improves user confide
```suggestion
A small Debt Auction Bid Size would result in an auction being triggered more quickly when the protocol is undercollateralized. If the protocol is quickly recollateralized, this may improve user confidence in Dai. A small Debt Auction Bid Size also means that gas costs for the auction would decrease the profit that keepers receive. In the event of a large system debt, this could also result in many parallel auctions, and keepers may not be able to participate in all of them. Both of these could result in uncompetitive auctions with more MKR minted than necessary.
```

2022-11-16 18:16 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-size.md
> +Adjusting the Debt Auction Bid Size parameter is a manual process that requires an executive vote. Changes to the Debt Auction Bid Size are subject to the [GSM Pause Delay](https://longforwisdom.gitb
Don't link to the staging site, lol. Relative links!

2022-11-16 18:16 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-size.md
> +A large Debt Auction Bid Size keeps the protocol undercollateralized for longer. Furthermore, keepers may find it harder to organize sufficient capital to participate in the debt auction if this para
```suggestion
A large Debt Auction Bid Size keeps the protocol undercollateralized for longer. Furthermore, keepers may find it harder to organize sufficient capital to participate in the debt auction if this parameter is too large. This lack of competition could result in more MKR minted. In the extreme case, too large a Debt Auction Bid Size would prevent debt auctions from taking place. However, when this parameter is large, the gas costs paid by the keepers to participate in the auction are small relative to their profit. In the case of large system debt, there would also be fewer auctions running in parallel and, therefore, a higher participation rate among keepers. Both of these could result in more competitive bids and decrease the amount of MKR minted. 
```

2022-11-16 18:16 UTC, LongForWisdom commented on parameter-index/debt-auction/param-lot-size-increase.md
> +Debt Auctions are used to recapitalize the system by minting and auctioning off MKR for a fixed amount of DAI. In this process, keepers bid on how little MKR they are willing to accept for the fixed
You're missing a link here?

2022-11-16 18:16 UTC, LongForWisdom commented on parameter-index/debt-auction/param-lot-size-increase.md
> +Adjusting the Debt Auction Lot Size Increase parameter is a manual process that requires an executive vote. Changes to the Debt Auction Lot Size Increase are subject to the [GSM Pause Delay](https://
Relative links!

2022-11-16 18:23 UTC, blimpa commented on parameter-index/debt-auction/param-bid-size.md
> +Adjusting the Debt Auction Bid Size parameter is a manual process that requires an executive vote. Changes to the Debt Auction Bid Size are subject to the [GSM Pause Delay](https://longforwisdom.gitb
no idea how that happened haha

2022-11-18 15:24 UTC, LongForWisdom requested changes
Make sure to read over what you've changed yourself Pablo, you can catch a lot of these errors just by double-checking yourself.

2022-11-18 15:24 UTC, LongForWisdom commented on parameter-index/debt-auction/param-bid-size.md
> +Adjusting the Debt Auction Bid Size parameter is a manual process that requires an executive vote. Changes to the Debt Auction Bid Size are subject to the [GSM Pause Delay](../core/param_gsm_pause_de
These should be hyphens not underscores. Please check that links work on the staging branch. That's one of the main positives for using it.

2022-11-18 15:24 UTC, LongForWisdom commented on parameter-index/debt-auction/param-lot-size-increase.md
> +Debt Auctions are used to recapitalize the system by minting and auctioning off MKR for a fixed amount of DAI. In this process, keepers bid on how little MKR they are willing to accept for the fixed
Initial lot size isn't `pad`?

2022-11-18 15:24 UTC, LongForWisdom commented on parameter-index/debt-auction/param-lot-size-increase.md
> +Debt Auctions are used to recapitalize the system by minting and auctioning off MKR for a fixed amount of DAI. In this process, keepers bid on how little MKR they are willing to accept for the fixed
This is pad and it's the increase amount.

2022-11-18 15:24 UTC, LongForWisdom commented on parameter-index/debt-auction/param-lot-size-increase.md
> +Adjusting the Debt Auction Lot Size Increase parameter is a manual process that requires an executive vote. Changes to the Debt Auction Lot Size Increase are subject to the [GSM Pause Delay](../core/
These should be hyphens not underscores. Please check that links work on the staging branch. That's one of the main positives for using it.

2022-11-18 15:24 UTC, LongForWisdom commented on parameter-index/debt-auction/param-min-bid-decrease-flop.md
> +A large Auction Debt Min Bid Decrease ensures high keeper participation as there is an opportunity for a larger profit. It also helps to balance other costs to the keeper when making a bid, such as t
Debt Auction rather than Auction Debt?

2022-11-21 17:21 UTC, LongForWisdom approved these changes

2022-11-21 17:23 UTC, merged