FOR REVIEW: Summary, readme, stability fee and impact estimations
makerdao/governance-manual pull request #221
Opened 2022-11-18 16:53 UTC by astronautthis

Staging PR: https://github.com/makerdao/governance-manual/pull/219
Summary: No staging link
Readme: No staging link
Impact estimations: No staging link - should this be added to summary.md?
Stability fee: https://longforwisdom.gitbook.io/new-collection/parameter-index/vault-risk/param-stability-fee
Minor correction in the How to vote video page: https://longforwisdom.gitbook.io/new-collection/governance/voting-in-makerdao/how-to-vote

2022-11-21 17:58 UTC, LongForWisdom requested changes
You also need to update the preamble on the Stability Fee Parameter page. There is a checklist of stuff to check for parameter docs on the MOM group work tracking sheet.

2022-11-21 17:58 UTC, LongForWisdom commented on README.md
> +Description: >-
Check that this doesn't break anything on staging. I don't think this is a visible piece of text, it's a key to tell gitbooks to display something in a certain way.

2022-11-21 17:58 UTC, LongForWisdom commented on governance/how-to-vote.md
> +>Page last reviewed: 2022-09-29
imo this is just a video link, if it worked when you checked it, also update the reviewed date.

2022-11-21 17:58 UTC, LongForWisdom commented on governance/impact_estimations.md
> +# Impact Estimations
filename should match the convention of using hyphens. so impact-estimations.md

2022-11-21 17:58 UTC, LongForWisdom commented on governance/impact_estimations.md
> +![](https://i.imgur.com/O6Yyz10.png)
We should use an image that doesn't show me as a governance facilitator imo. Also, don't use imgur for links. You need to include the image in the repo and link to it using a relative link.

2022-11-21 17:58 UTC, LongForWisdom commented on governance/impact_estimations.md
> +## Usage
You should update this section, they are currently used on the voting portal, and I think there are a couple of other place we surface them. I think:
* Forum
* Voting Portal
* Hernando's frontend?
* That tracking sheet.

2022-11-21 17:58 UTC, LongForWisdom commented on governance/impact_estimations.md
> +![](https://i.imgur.com/O6Yyz10.png)
Maybe include images for the voting portal and hernando's dashboard as well?

2022-11-21 17:58 UTC, LongForWisdom commented on governance/impact_estimations.md
> +# Impact Estimations
Note remember to add this to the main MOM tracking spreadsheet, and to ensure that it's set to mark itself NEEDS REVIEW in a year.

2022-11-21 17:58 UTC, LongForWisdom commented on governance/impact_estimations.md
> +In the future, these may be integrated these into the [voting portal](https://vote.makerdao.com) as well.
Already happened, as commented above.

2022-11-21 17:58 UTC, LongForWisdom commented on parameter-index/vault-risk/param-stability-fee.md
> +The Rates Working Group has been empowered by Maker Governance to propose rate changes based on monetary policy, risk, and competitive landscape. The operations, membership, and historic proposals of
This has been called the Maker Open Market Committee for a good while, we should use that term, imo. Also, I'm like 90% sure there is a tag on the forum with all MOMC related stuff under it. We should link directly to that tag.

2022-11-21 21:01 UTC, astronautthis commented
@LongForWisdom not sure where to put impact-estimations.md on the navigation pane. I put it under "voting-in-makerdao" for now but feel free to move it if you think it fits better elsewhere. 

Also, could you take a look at the images in impact-estimations.md if they're okay? Thanks!

2022-11-23 17:39 UTC, LongForWisdom commented
You've somehow got some other stuff mixed up in here.

2022-11-23 18:06 UTC, LongForWisdom commented on SUMMARY.md
> +  * [Impact Estimations](governance/impact-estimations.md)
I'm not sure where else we'd put this, but also doesn't quite feel like it fits. Hm. Definitely wondering if we need to rearrange the Governance section.

2022-11-23 22:47 UTC, astronautthis commented on governance/impact-estimations.md
> +* Provide appropriate context for GovAlpha members conducting internal reviews of governance items.
You mean the second bullet point about internal reviews, yeah? And keep line 3 that says "GovAlpha applies impact estimations" as is.

2022-11-24 00:19 UTC, astronautthis commented on governance/impact-estimations.md
> +## Usage
I'm not sure exactly why this is happening but notice the following two commits and the image of the Governance tracker spreadsheet:

1. https://github.com/astronautthis/governance-manual/blob/8b2c29f58cc49328c9fc7abc2be9d6079e6f6ffd/governance/impact-estimations.md

2. https://github.com/astronautthis/governance-manual/blob/e1b1046e492183ea33dd3afcc788fb2da562a205/governance/impact-estimations.md

The image size does change in the two files but I checked that the staging link size stays the same (the small version). Maybe there's some image sizing override happening on GitBook?

2022-11-24 00:23 UTC, astronautthis commented on governance/impact-estimations.md
> +## Usage
The issue is described here: https://github.com/Open-Systems-Pharmacology/docs/issues/60

2022-11-24 00:25 UTC, astronautthis commented on SUMMARY.md
> +  * [Impact Estimations](governance/impact-estimations.md)
Yes, I think we should.

2022-11-25 15:16 UTC, LongForWisdom commented on governance/impact-estimations.md
> +## Usage
So, I think you can add whitespace to make them more square, but agree it's a sucky way to 'fix' it.

2022-11-25 15:17 UTC, LongForWisdom commented on governance/impact-estimations.md
> +## Usage
Either that or take screenshots that are more square

2022-11-25 15:17 UTC, LongForWisdom commented on parameter-index/vault-risk/param-stability-fee.md
>  Adjusting a Stability Fee parameter is a manual process that requires an executive vote. Changes to Stability Fee parameters are subject to the GSM Pause Delay.
You should link to the GSM page from here.

2022-11-25 17:06 UTC, astronautthis commented on governance/impact-estimations.md
> +## Usage
Fixed now

2022-11-25 17:14 UTC, astronautthis commented
Adding Emergency Shutdown: [Staging link](https://longforwisdom.gitbook.io/new-collection/module-index/module-emergency-shutdown)

2022-12-02 14:45 UTC, LongForWisdom approved these changes

2022-12-02 14:46 UTC, merged