DRAFT: GSM Exceptions
makerdao/governance-manual pull request #233
Opened 2022-11-25 15:39 UTC by LongForWisdom

Staging Link:
https://longforwisdom.gitbook.io/new-collection/governance/verification/gsm-exceptions

2022-11-25 15:53 UTC, LongForWisdom commented
Need to remember to add this to the tracking sheet

2022-11-25 15:54 UTC, LongForWisdom commented
@jpritikin feel free to review.

2022-11-26 21:42 UTC, kmbarry1 commented on governance/gsm-exceptions.md
> +This functionality is exceptional to give Maker Governance a chance to limit the lost value if the target protocol or entity for a D3M becomes insolvent. Because targets are often publicly accessible
Instead of "likely close to" I'd personally phrase it as just "up to".

2022-11-26 21:47 UTC, kmbarry1 commented on governance/gsm-exceptions.md
> +Additionally, the contact allows for permissionless activation of the circuit breaker, if the price decrease in a collateral exceeds a preset value between oracle price updates.
I'd be explicit that the permissionless action does not allow the level to be selected, but rather sets it to level 2. This is because new liquidations and resets directly depend on the current oracle price, whereas purchases from active auctions do not.

Also I'd clarify that the price decrease threshold for permissionless activation is percentage-based. While that's the only logical way for it to work, I've learned the hard way to never underestimate the potential for confusion that can arise from less-than-perfectly precise wording.

2022-11-26 21:51 UTC, kmbarry1 commented on governance/gsm-exceptions.md
> +* The reason for the exceptional functionality.
One general thing to consider adding to all module entries: the risks associated with using each module. This is particularly important as a malicious governance action might use these modules inappropriately to harm the system.

2022-12-04 02:21 UTC, astronautthis commented on governance/gsm-exceptions.md
> +The risk opened up by this exceptional functionality is that the oracles may be frozen by an attacker in order to either:
Did you mean that liquidations may be disabled, not oracles frozen?

2022-12-05 16:13 UTC, LongForWisdom commented on governance/gsm-exceptions.md
> +The risk opened up by this exceptional functionality is that the oracles may be frozen by an attacker in order to either:
Well spotted, fixed, thank you!

2022-12-06 20:31 UTC, blimpa requested changes

2022-12-06 20:31 UTC, blimpa commented on governance/gsm-exceptions.md
> +The `MCD_PAUSE` contract manages the timelock functionality of the [GSM Pause Delay](../parameter-index/core/param-gsm-pause-delay.md), however, it also contains an in-built exception to its own rule
```suggestion
The `MCD_PAUSE` contract manages the timelock functionality of the [GSM Pause Delay](../parameter-index/core/param-gsm-pause-delay.md); however, it also contains an in-built exception to its own rule.
```

2022-12-06 20:31 UTC, blimpa commented on governance/gsm-exceptions.md
> +This functionality allows Maker governors to prevent a malicious attack on the protocol if they are able to exceed the attacker's MKR weight before the [GSM Pause Delay](../parameter-index/core/param
"Maker governors" = what we're calling "Maker Governance" everywhere else, so I think it's probably better to keep calling them that

2022-12-06 20:31 UTC, blimpa commented on governance/gsm-exceptions.md
> +The risk opened up by this exceptional functionality is that a malicious attacker may be able to delay or permanently block a legitimate governance proposal that negatively affects them.
```suggestion
The risk opened up by this exceptional functionality is that a malicious attacker may be able to delay or permanently block a legitimate governance proposal.
```

2022-12-06 20:31 UTC, blimpa commented on governance/gsm-exceptions.md
> +This functionality gives Maker Governance a chance to prevent a malicious oracle price from causing liquidations (or unbacked DAI minting) in the Maker Protocol. Due to the structure of Maker's oracl
```suggestion
This functionality gives Maker Governance a chance to prevent a malicious oracle price from causing liquidations or the minting of unbacked DAI in the Maker Protocol. Due to the structure of Maker's oracles, the next oracle value is known one hour in advance of it becoming active in the Protocol. This is the window in which Maker Governance can act to prevent a malicious oracle price from entering the protocol.
```

2022-12-06 20:31 UTC, blimpa commented on governance/gsm-exceptions.md
> +This functionality is exceptional so that the Maker protocol can react to changes in debt demand more quickly than waiting for the GSM delay.
```suggestion
This functionality gives the Maker protocol the ability to react to changes in debt demand more quickly than is possible waiting for the GSM delay.
```

2022-12-06 20:31 UTC, blimpa commented on governance/gsm-exceptions.md
> +The circuit breaker functionality allows a successful governance proposal to impose governance's choice of limitations on liquidations for any or all of the vault types in the Maker Protocol.
```suggestion
The circuit breaker functionality allows a successful governance proposal to impose Maker Governance's choice of limitations on liquidations for any or all of the vault types in the Maker Protocol.
```

2022-12-06 20:31 UTC, blimpa commented on governance/gsm-exceptions.md
> +Additionally, the contact allows for permissionless activation of the circuit breaker, if the price decrease in a collateral exceeds a preset percentage value between oracle price updates. The permis
```suggestion
Additionally, the contract allows for permissionless activation of the circuit breaker, if the price decrease in a collateral exceeds a preset percentage value between oracle price updates. The permissionless activation triggers the circuit breaker at Level 2 because both new auctions and resets reference the current oracle price. 
```

2022-12-06 20:31 UTC, blimpa commented on governance/gsm-exceptions.md
> +This functionality is exceptional because liquidations at non-market prices have the potential to be irreversibly damaging to both users and the Maker Protocol. The circuit breaker allows Maker gover
```suggestion
This functionality is exceptional because liquidations at non-market prices have the potential to be irreversibly damaging to both users and the Maker Protocol. The circuit breaker allows Maker Governance to attempt to limit the damage in the event of an issue affecting liquidations without waiting for the [GSM Pause Delay](../parameter-index/core/param-gsm-pause-delay.md).
```

2022-12-06 20:31 UTC, blimpa commented on governance/gsm-exceptions.md
> +This functionality is exceptional to give Maker Governance a chance to limit the lost value if the target protocol or entity for a D3M becomes insolvent. Because targets are often publicly accessible
```suggestion
This functionality is exceptional to give Maker Governance a chance to limit the lost value if the target protocol or entity for a D3M becomes insolvent. Because targets are often publicly accessible protocols there is likely to be a race to extract as much value as possible in the event of a hack or insolvency event. Waiting for the [GSM Pause Delay](../parameter-index/core/param-gsm-pause-delay.md) to expire makes it likely that the Maker Protocol will lose significant value &mdash; up to the maximum debt ceiling on the D3M. 
```

2022-12-07 15:32 UTC, LongForWisdom commented on governance/gsm-exceptions.md
> +This functionality is exceptional so that the Maker protocol can react to changes in debt demand more quickly than waiting for the GSM delay.
Gonna stick with the wording on this one. Have used it multiple times in the doc and it highlights that fact that it's doing something out of the usual.

2022-12-07 15:35 UTC, LongForWisdom commented
Fixed most of those. Thanks Pablo!

2022-12-09 12:23 UTC, patrick-j-govalpha requested changes
Mostly looks fine to me. See comments:

One other thing, the word "functionality" is used 31 times in this doc, is there a synonym that could be occasionally be sprinkled in for style/readability reasons? It felt a bit clunky to read at times. However, this is likely personal preference so feel free to ignore

2022-12-09 12:23 UTC, patrick-j-govalpha commented on SUMMARY.md
>  * Verification
I don't love the placement in the "verification" category.

Like if I was looking for GSM Exceptions I wouldn't expect it to be here. Is there an alternative location it would be better?

Or fork out all the Executive Vote stuff into a new "Executive Vote" category?

2022-12-09 12:23 UTC, patrick-j-govalpha commented on governance/gsm-exceptions.md
> +# GSM Pause Delay Exceptions
Add relative link to this entry from the GSM delay parameter doc?

2022-12-12 17:17 UTC, LongForWisdom commented on SUMMARY.md
>  * Verification
Yeah, I wasn't sure. I can't think of a better place right now. I might reorganize them soon.

2022-12-14 15:49 UTC, merged