FOR REVIEW: Emergency Shutdown doc
makerdao/governance-manual pull request #257
Opened 2022-12-05 17:22 UTC by astronautthis

Staging link: https://longforwisdom.gitbook.io/new-collection/governance/voting-in-makerdao/emergency-shutdown

2022-12-06 14:45 UTC, LongForWisdom requested changes
See comments. Despite my nit-picking, you did a great job!

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +An important security feature of the Maker Protocol is the ability to perform an Emergency Shutdown of the protocol. This allows the system to shut down and makes underlying collateral available for
I would go into more detail here. The goal is to shut down the protocol in as graceful a way as possible, making sure everyone receives their share of the value within it. Probably don't just write that, think about how to word it better. I think the idea to get across is that the goal is to avoid screwing anyone, and if people have to get screwed (because the protocol is insolvent), then DAI holders are screwed as equitably as possible, lol.

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +1. Once Emergency Shutdown has been activated, the following items take effect immediately:
```suggestion
1. Once Emergency Shutdown has been activated, the following changes take place immediately:
```

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +    * Vault owners may withdraw any excess collateral from their vaults.
Should reword this. By default vault owners can always do this, so it isn't a change or effect of shutdown. Really, vault owners lose access to the part of their collateral that is required to back DAI given current oracle prices.

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +2. Once Emergency Shutdown has been activated, a cooldown period is needed to allow any ongoing collateral auctions to conclude. Once all collateral auctions finish, the system can calculate the coll
How are vault owners able to withdraw part of their collateral prior to this calculation?

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +    * Vault owners may withdraw any excess collateral from their vaults.
Maybe this isn't true? See comment below.

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +# Emergency Shutdown
I think we add a disclaimer to this one.

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +# Emergency Shutdown
(see GSM exceptions doc)

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +3. Each DAI holder will then be able to redeem collateral through a series of individual transactions for each collateral type.
Or sell DAI in a secondary market?

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +Since the Maker Protocol is open source and decentralized, anyone can redeploy the system and decide with what configuration. Ideally, the parameters of redeployment should depend on the reason for t
Reword: "Since the Maker Protocol is open source and decentralized, anyone can redeploy the system and decide with what configuration." Sounds awkward.

Maybe highlight that MKR holders would probably vote on a redeployment + configuration?

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +DAI is no longer soft pegged to 1 USD after Emergency Shutdown, as it is now tied to the value of a fixed amunt of underlying collateral. Such a depegging can result in significant disruption across
can result -> could result (I think)

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +DAI holders need to manually redeem their DAI for the underlying collateral. The process is not automatic. Similarly, vault owners must manually withdraw any excess collateral from their vaults.
Or sell on secondary markets, or keep it. DAI is still fully transferrable after shutdown.

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +MKR tokens are not expected to have value after the system is shut down. If the protocol is relaunched and the community decides to do so, existing MKR holders, including those who burned their MKR b
If there is a vote on re-launch parameters, it may have some value. It's actually pretty hard to say on this. Very much depends whether MKR is kept as the new governance token, or if there is a migration, and if there is a migration, if it's at a particular date, or if it's redeem old MKR for new MKR on an ongoing basis.

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +Real-world Assets are represented by RWA tokens and DAI holders may redeem the tokens which represent a fractional share of their ownership of the corresponding asset.
placeholder RWA tokens? You're implying the RWA tokens can be redeemed here, which as I understand is not a guarantee.

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +3. Each DAI holder will then be able to redeem collateral through a series of individual transactions for each collateral type.
Wait actually, is this even true? My understanding was that you redeemed DAI for a share of the collateral basket in one transaction. Otherwise everything seems very strange to me. Did this come from a technical source?

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +Technical documentation about how Emergency Shutdown works can be found in the [Emergency Shutdown Module](https://docs.makerdao.com/smart-contract-modules/emergency-shutdown-module) section and [End
Maybe just a bullet list here instead?

2022-12-06 14:45 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +3. Each DAI holder will then be able to redeem collateral through a series of individual transactions for each collateral type.
Right, I checked the docs, this is true, but the way you've written it is a little misleading. This implies that a DAI holder can redeem all their DAI for a specific collateral if there is any of that collateral 'left', which is incorrect. In fact, the DAI holder calls some functions, exchanges their DAI for what is effectively an NFT, and that NFT then gives them permission to withdrawal a pro-rata share of collateral from each collateral type.

2022-12-10 22:44 UTC, astronautthis commented on governance/emergency-shutdown.md
> +# Emergency Shutdown
I added one at the end since the disclaimer at the start felt a bit too distracting. Happy to move it if you feel it should be at the start though

2022-12-10 22:58 UTC, astronautthis commented on governance/emergency-shutdown.md
> +    * All debt and surplus auctions are disabled.
Yes, including active auctions. The following is from https://docs.makerdao.com/smart-contract-modules/shutdown/end-detailed-documentation "Flap and flop auctions are frozen by the initial cage(). Both Flap and Flop auctions can be yanked to return the bids to the last bidder." Let me know if this is unclear or I misunderstood something.

2022-12-10 23:08 UTC, astronautthis commented on governance/emergency-shutdown.md
> +2. Once Emergency Shutdown has been activated, a cooldown period is needed to allow any ongoing collateral auctions to conclude. Once all collateral auctions finish, the system can calculate the coll
So for vaults with ongoing collateral auctions at the time of ES, their vault must already be undercollateralized, which means their excess collateral amount is zero. So these guys aren't able to withdraw anything because they have no excess collateral. 

Any vault that is overcollateralized according to the current oracle price at the time `cage()` is called can withdraw their excess collateral (as quantified by the oracle price at the moment of ES).

2022-12-10 23:08 UTC, astronautthis commented on governance/emergency-shutdown.md
> +    * Vault owners may withdraw any excess collateral from their vaults.
Good point, I should make this clearer

2022-12-10 23:10 UTC, astronautthis commented on governance/emergency-shutdown.md
> +3. Each DAI holder will then be able to redeem collateral through a series of individual transactions for each collateral type.
Yes, that's what I meant but I realize it's phrased poorly. Will edit.

2022-12-12 15:50 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +While all reasonable effort has been made to ensure the accuracy and currency of this page, the authors are not smart contract developers, and changes to the Emergency Shutdown procedure may be made
You can use the fancy syntax for this, and maybe move it closer to the top.

2022-12-12 15:54 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +While all reasonable effort has been made to ensure the accuracy and currency of this page, the authors are not smart contract developers, and changes to the Emergency Shutdown procedure may be made
I think there's an example in the GSM shutdown PR.

2022-12-12 15:54 UTC, LongForWisdom commented on governance/emergency-shutdown.md
> +# Emergency Shutdown
Maybe after the overivew?

2022-12-14 15:40 UTC, LongForWisdom approved these changes

2022-12-14 16:59 UTC, merged