add monetalis clydesdale to RWA collaterals
makerdao/governance-manual pull request #274
Opened 2023-02-24 13:12 UTC by patrick-j-govalpha

staging: https://longforwisdom.gitbook.io/new-collection/collateral/real-world-assets-in-detail/monetalis-clydesdale

2023-02-27 14:45 UTC, LongForWisdom requested changes

2023-02-27 14:45 UTC, LongForWisdom commented on collateral/monetalis-clydesdale.md
> +The DAI loan is collateralized 1:1 with US Treasuries, althought the true collateralization ratio may vary with the value of the underlying holdings.
```suggestion
The DAI loan is collateralized 1:1 with US Treasuries, although the true collateralization ratio may vary with the value of the underlying holdings.
```

2023-02-27 14:45 UTC, LongForWisdom commented on collateral/monetalis-clydesdale.md
> +On a quarterly basis, surplus treasuries should be sold and the excess returned to the Surplus Buffer, marking profits for MakerDAO and MKR holders.
```suggestion
On a quarterly basis, surplus treasuries are sold and the excess returned to the Surplus Buffer, marking profits for MakerDAO and MKR holders.
```

2023-02-27 14:45 UTC, LongForWisdom commented on collateral/monetalis-clydesdale.md
> +On a quarterly basis, surplus treasuries should be sold and the excess returned to the Surplus Buffer, marking profits for MakerDAO and MKR holders.
Not sure if this is actually the case. But having 'this should happen' in the docs is not ideal.

2023-02-27 14:45 UTC, LongForWisdom commented on collateral/monetalis-clydesdale.md
> +A Dune dashboard displaying the status of the deal may be viewed [here](https://dune.com/SebVentures/makerdao-mip65).
Also link to this? <https://forum.makerdao.com/t/mip65-monetalis-clydesdale-documentation-hq/17923>

2023-02-27 14:46 UTC, LongForWisdom commented on collateral/monetalis-clydesdale.md
> +>Next review due: 2024-02-24
I think I had the others of these as quarterly updates, given RWA stuff is changing semi-regularly.

2023-03-02 12:13 UTC, patrick-j-govalpha commented on collateral/monetalis-clydesdale.md
> +On a quarterly basis, surplus treasuries should be sold and the excess returned to the Surplus Buffer, marking profits for MakerDAO and MKR holders.
agree, the reason I went with should is because there is a chance that they aren't, since it's not controlled by smart contracts we can't enforce it with code. Happy to change though

2023-03-02 12:18 UTC, patrick-j-govalpha commented
updated - changes merged to staging - https://longforwisdom.gitbook.io/new-collection/collateral/real-world-assets-in-detail/monetalis-clydesdale

2023-03-03 10:59 UTC, merged