update d3m doc
makerdao/governance-manual pull request #276
Opened 2023-02-24 16:15 UTC by patrick-j-govalpha

assistance from chatgpt

staging: https://longforwisdom.gitbook.io/new-collection/module-index/module-dai-direct-deposit

2023-02-27 14:59 UTC, LongForWisdom requested changes

2023-02-27 14:59 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
> +>**Scope:** A contract (or set of contracts) per deposit target.
```suggestion
>**Scope:** A set of secondary contracts per deposit target.  
```

2023-02-27 14:59 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
> +>**Secondary Contracts:** Numerous
Just list the other contract template names? Also, should use the chainlog names to match with other docs.

![image](https://user-images.githubusercontent.com/53664591/221596018-583aebfc-8934-40a0-bb0e-aa7acdc4c2ab.png)

In places where there are multiple contracts that are templated, we use dollarsign to represent a parameter. Ie:

![image](https://user-images.githubusercontent.com/53664591/221596307-efeddfea-feea-43f5-8644-5107f92a6556.png)

Suggest DIRECT_$TARGET_DAI_POOL/PLAN/ORACLE in this case.

2023-02-27 14:59 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
> +Further, it allows Maker the potential to undercut centralized stablecoins on these lending protocols. By providing DAI directly on other lending protocols, Maker could ensure that the borrow rate fo
```suggestion
Further, it gives Maker the ability to undercut centralized stablecoins on these lending protocols. By providing DAI directly on other lending protocols, Maker can ensure that the borrow rate for DAI on those protocols is almost always below the borrow rate for centralized stablecoins. 
```

2023-02-27 14:59 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
> +## Technical Information
Not sure this is necessary at this level of documentation? At the least, it's less important than the parameters, and should appear lower down in the document.

2023-02-27 14:59 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
> +### Formulas
You removed the Target Borrow rate here? Might make sense to go, but if so, spread should probably come out of meta-parameters as well.

2023-03-02 12:36 UTC, patrick-j-govalpha commented on module-index/module-dai-direct-deposit.md
> +>**Secondary Contracts:** Numerous
fixed

2023-03-02 12:37 UTC, patrick-j-govalpha commented on module-index/module-dai-direct-deposit.md
> +>**Secondary Contracts:** Numerous
also changed D3M_HUB to DIRECT_HUB to match the chainlog

2023-03-02 12:37 UTC, patrick-j-govalpha commented on module-index/module-dai-direct-deposit.md
> +## Technical Information
moved lower down, this was one of chatgpt's additions

2023-03-02 12:39 UTC, patrick-j-govalpha commented on module-index/module-dai-direct-deposit.md
> +### Formulas
Yeah putting it back in, should've changed it rather than removing it. It was still the old formula that accounted for staking rewards etc

2023-03-02 12:42 UTC, patrick-j-govalpha commented
updated - staging also updated - https://longforwisdom.gitbook.io/new-collection/module-index/module-dai-direct-deposit

2023-03-02 17:27 UTC, LongForWisdom commented on module-index/module-dai-direct-deposit.md
> +## Technical Information
Maybe use the chainlog names here as well? Not super worried though.

2023-03-02 17:27 UTC, LongForWisdom approved these changes
Left one comment. Doesn't need to block the update though, imo.

2023-03-03 10:59 UTC, patrick-j-govalpha commented on module-index/module-dai-direct-deposit.md
> +## Technical Information
I thought in main text we were trying to stick to human readable names?

2023-03-03 10:59 UTC, merged