FOR REVIEW: Update mips.md
makerdao/governance-manual pull request #300
Opened 2023-05-24 13:58 UTC by blimpa

Staging link: https://longforwisdom.gitbook.io/new-collection/makerdao/structure/mips

2023-05-24 14:05 UTC, astronautthis commented on governance/mips.md
> +## Historical Aside and Current State
```suggestion
## Current State
```

2023-05-24 14:07 UTC, astronautthis commented on governance/mips.md
> +## Historical Aside and Current State
I would start with the current state i.e. there are 17 MIPs and add a note about the historical state i.e. that the Endgame Plan made many older MIPs obsolete.

2023-05-24 14:09 UTC, astronautthis commented on governance/mips.md
> +The MIP Framework (a once large and ever-growing pool of 100+ documents) has been the legislative backbone of MakerDAO since April 2020. In view of recent changes introduced by the Endgame (which aff
Please link to https://endgame.makerdao.com/endgame/overview when it first appears

2023-05-24 14:10 UTC, astronautthis commented on governance/mips.md
> +- The MIP Framework has been relatively locked in place, with no new MIPs allowed in addition to the 17 that are still active. These MIPs are transitionally known as Endgame MIPs.
Not sure about the phrasing "relatively locked in place". Consider simpler language or just start with the statement that no new MIPs are allowed?

2023-05-24 14:12 UTC, astronautthis commented on governance/mips.md
> +- The MIP Framework has been relatively locked in place, with no new MIPs allowed in addition to the 17 that are still active. These MIPs are transitionally known as Endgame MIPs.
Would also avoid the transitional nomenclature and instead use whatever word the Atlas uses for Endgame MIPs i.e. whatever replaced Scope Frameworks

2023-05-24 14:12 UTC, astronautthis commented on governance/mips.md
> +- Out of the 17 Endgame MIPs, some are due to be deprecated as the Endgame further establishes itself.
Delete line, it's mentioned later in the list anyway

2023-05-24 14:19 UTC, astronautthis commented on governance/mips.md
> +| [MIP106: Support Scope Bounded Mutable Alignment Artifact](https://mips.makerdao.com/mips/details/MIP106) |  MIP106 defines the Support Scope, which covers rules that regulate various tasks of ecos
```suggestion
| [MIP106: Support Scope Bounded Mutable Alignment Artifact](https://mips.makerdao.com/mips/details/MIP106) |  MIP106 defines the Support Scope, which covers rules that regulate various tasks of ecosystem support, including governance process infrastructure and management, SubDAO and Ecosystem Actor support, and the Public Good Purpose System | N/A |
```

2023-05-24 14:20 UTC, astronautthis commented on governance/mips.md
> +| [MIP0: Maker Improvement Proposal Framework](https://mips.makerdao.com/mips/details/MIP0) | MIP0 defines the Maker Improvement Proposals (MIPs) Framework for all subsequent MIPs to utilize | N/A |
In the second column, you don't need to repeat the MIP number since it's already in the first column e.g., change "MIP0 defines the... " to "Defines the...".

2023-06-27 11:57 UTC, patrick-j-govalpha commented on governance/mips.md
> +| [* MIP55: Special Purpose Fund](https://mips.makerdao.com/mips/details/MIP55) | MIP55 defines Special Purpose Funda (SPFs), a tool used to fulfill a narrow, specific, or temporary objective where a
put these in numerical order

2023-06-27 11:57 UTC, patrick-j-govalpha requested changes
see comment

2023-07-26 16:22 UTC, patrick-j-govalpha approved these changes

2023-07-26 16:22 UTC, merged