General clean-up
makerdao/governance-manual pull request #327
Opened 2023-08-24 14:35 UTC by LongForWisdom

* Removed obviously out of date information.
* Added disclaimers where most information is still good.
* Moved some pages we will need new versions of to 'needs-rewrite' folder, and removed from navigation.

Visible on staging site here: <https://longforwisdom.gitbook.io/new-collection/v/clean-up-temp/>

2023-08-24 16:00 UTC, patrick-j-govalpha requested changes

2023-08-25 14:33 UTC, astronautthis commented on governance/impact-estimations.md
> +The Governance Facilitators apply impact estimations to active governance items (MIPs and Signal Requests). The goal of these estimations is to provide alignment conservers and the wider community wi
I was gonna delete this page since we aren't really doing it?

2023-08-25 14:36 UTC, blimpa commented on needs-rewrite/mips.md
What do you think needs to be modified here?

2023-08-25 14:42 UTC, astronautthis approved these changes

2023-08-25 14:46 UTC, merged