FOR REVIEW: Adding Endgame stuff
makerdao/governance-manual pull request #335
Opened 2023-08-28 18:08 UTC by astronautthis

Staging links:
https://longforwisdom.gitbook.io/new-collection/
https://longforwisdom.gitbook.io/new-collection/governance-elements/atlas
https://longforwisdom.gitbook.io/new-collection/governance-elements/scopes-and-artifacts
https://longforwisdom.gitbook.io/new-collection/governance-elements/list-of-scopes
https://longforwisdom.gitbook.io/new-collection/governance-elements/scope-advisory-councils
https://longforwisdom.gitbook.io/new-collection/resources/easy-governance-frontend
https://longforwisdom.gitbook.io/new-collection/delegation/overview/what-is-delegation
https://longforwisdom.gitbook.io/new-collection/delegation/entities/alignment-conservers
https://longforwisdom.gitbook.io/new-collection/delegation/entities/avc
https://longforwisdom.gitbook.io/new-collection/delegation/entities/aligned-delegates

Sorry for large number of links but it's mostly copy-pasting from Endgame Docs

2023-08-29 14:00 UTC, LongForWisdom commented on SUMMARY.md
> +  * [Alignment Conservers](delegation/alignment-conservers.md)
Not sure this belongs under delegation.

2023-08-29 14:00 UTC, LongForWisdom commented on delegation/delegate-metric-tracking.md
> +# Delegate Metric Tracking
Imo we should just delete these pages now, given that there is not an active plan in place to fund the creation of this documentation.

2023-08-29 14:00 UTC, LongForWisdom commented on delegation/what-is-delegation.md
> +# What is Delegation?
Imo we should just delete these pages now, given that there is not an active plan in place to fund the creation of this documentation.

2023-08-29 14:00 UTC, LongForWisdom commented on governance/easy-governance-frontend.md
> +# Easy Governance Frontend
Imo we should just delete these pages now, given that there is not an active plan in place to fund the creation of this documentation.

2023-08-29 14:00 UTC, LongForWisdom commented on governance/old/impact-estimations.md
I think we should keep this, we still use the impact tags on the polls, and that still feels useful.

2023-08-29 14:00 UTC, LongForWisdom commented on governance/scope-advisory-councils.md
> +# Scope Advisory Councils
Imo we should just delete these pages now, given that there is not an active plan in place to fund the creation of this documentation.

2023-08-29 14:00 UTC, LongForWisdom commented on governance/scopes-and-artifacts.md
> +# Scopes and Scope Artifacts
Tie into the list of scopes, maybe. Probably doesn't need to be two pages now.

2023-08-30 13:18 UTC, astronautthis commented on SUMMARY.md
> +  * [Alignment Conservers](delegation/alignment-conservers.md)
I'll think about it but since AVCs and ADs are both Alignment Conservers, it seemed to be the most appropriate place to put it

2023-08-30 13:57 UTC, blimpa requested changes

2023-08-30 13:57 UTC, blimpa commented on delegation/aligned-delegates.md
> +Aligned Delegates (ADs) are anonymous [Alignment Conservers (AC)](alignment-conservers.md) who operate as delegates. They use [Protocol Delegation Modules (PDMs)](https://mips.makerdao.com/mips/detai
Maybe "of the AVCs they are affiliated with" or something like that?

2023-08-30 13:57 UTC, blimpa commented on delegation/aligned-delegates.md
> +- Writing AVC's governance strategy to capture the essence of AVC
```suggestion
- Writing AVC's governance strategy
```

2023-08-30 13:57 UTC, blimpa commented on delegation/aligned-delegates.md
> +- Writing elements for Aligned Scope Proposals to capture intent of the AVC and the Scope Advisory Council
Should these be plural? AVCs, Advisory Councils?

2023-08-30 13:57 UTC, blimpa commented on delegation/aligned-delegates.md
> +AD must be linked to at least two AVCs through GSLs. AD are displayed prominently in the EGF as followers of a AVC's Strategy, as long as they have two GSLs.
```suggestion
ADs must be linked to at least two AVCs through GSLs. ADs are displayed prominently in the EGF as followers of a AVC's Strategy, as long as they have two GSLs.
```

2023-08-30 13:57 UTC, blimpa commented on delegation/alignment-conservers.md
> +An Alignment Conserver (CC) is a guardian of the [Maker Atlas](../governance/atlas.md). They must preserve the Atlas and oppose any entities threatening it.
```suggestion
An Alignment Conserver (AC) is a guardian of the [Maker Atlas](../governance/atlas.md). They must preserve the Atlas and oppose any entities threatening it.
```

2023-08-30 13:57 UTC, blimpa commented on delegation/alignment-conservers.md
> +There are two types of Alignment Conservers, an [AVC](avc.md) Member and an [Aligned Delegate](aligned-delegates.md).
```suggestion
There are two types of Alignment Conservers: [AVC](avc.md) Members and [Aligned Delegates](aligned-delegates.md).
```

2023-08-30 13:57 UTC, blimpa commented on delegation/alignment-conservers.md
> +The Arbitration Scope gives recognition to each type of Alignment Conserver if they meet the requirements. Ecosystem Actors that become recognized as a type of Alignment Conserver may not assume any
Very confusing

2023-08-30 13:57 UTC, blimpa commented on delegation/alignment-conservers.md
> +An Alignment Conserver can be **derecognized** if it acts against the pledge or against any of the requirements attached to their type.
```suggestion
An Alignment Conserver can be **derecognized** if they act against the pledge or against any of the requirements attached to their type.
```

2023-08-30 13:57 UTC, blimpa commented on delegation/avc.md
> +Aligned Voter Committees (AVCs) are organized groups of MKR holders who have a shared strategic vision for the Maker protocol. Its members must be [Alignment Conservers](alignment-conservers.md).
```suggestion
Aligned Voter Committees (AVCs) are organized groups of MKR holders who have a shared strategic vision for the Maker protocol whose members are [Alignment Conservers](alignment-conservers.md).
```

2023-08-30 13:57 UTC, blimpa commented on delegation/avc.md
> +2. To ensure that all [Aligned Delegates (ADs)](aligned-delegates.md) that are affiliated with them, execute the AVC's strategic vision when voting on governance issues.
```suggestion
2. To ensure that all [Aligned Delegates (ADs)](aligned-delegates.md) that are affiliated with them execute the AVC's strategic vision when voting on governance issues.   
```

2023-08-30 13:57 UTC, blimpa commented on delegation/avc.md
> +The Hawk/Dove is a continuous spectrum, so many different hawkish or dovish AVCs can exist that are more or less balanced.
```suggestion
The Hawk/Dove spectrum is a continuous, so many different hawkish or dovish AVCs can exist that are more or less balanced.
```

2023-08-30 13:57 UTC, blimpa commented on delegation/avc.md
> +The documents produced by the AVCs abstract away the minutiae of day-to-day governance. Since Aligned Delegates execute AVC strategies, they allow MKR Holders to be reasonably informed and secure wit
Not really a non-sequitur, but looks like one at a glance

2023-08-30 13:57 UTC, blimpa commented on delegation/avc.md
> +AVC Members who fulfill these eligibility requirements and have the highest verified MKR ownership are eligible for compensation.
So only one AVC member is eligible for compensation, the one with the highest verified MKR ownership?

2023-08-30 13:57 UTC, blimpa commented on delegation/avc.md
> +The [Easy Governance Frontend (EGF)](../governance/easy-governance-frontend.md) displays AVCs on a list that ranks them by their voter weight. The voter weight is calculated by adding the verified MK
```suggestion
The [Easy Governance Frontends (EGFs)](../governance/easy-governance-frontend.md) display AVCs on a list that ranks them by their voter weight. The voter weight is calculated by adding the verified MKR holdings of members plus the MKR delegated to delegates that follow the AVC's Governance Strategy.
```

2023-08-30 13:57 UTC, blimpa commented on governance/scopes-and-artifacts.md
> +Scope Artifacts include *strengthening elements*, which ossify over time, and *mutable elements*, which are active elements related to governance, budget elements, and template elements.
Not too clear what "active" means here, I think

2023-08-30 13:57 UTC, blimpa commented on governance/scopes-and-artifacts.md
> +Scope Artifacts (GOV3) must include a ruleset for the ossification of mutable elements. Any **significant** change to the Scopes should take long and should allow enough time for feedback.
"(GOV3)" is confusing

2023-08-30 14:28 UTC, blimpa commented on delegation/alignment-conservers.md
> +## Eligibility requirements
```suggestion
## Eligibility Requirements
```

2023-09-01 16:06 UTC, astronautthis commented on delegation/delegate-metric-tracking.md
> +# Delegate Metric Tracking
I've confirmed with VoteWizard that there will be funding for these pages

2023-09-01 16:57 UTC, patrick-j-govalpha approved these changes
Good enough to ship IMO

2023-09-01 16:57 UTC, merged