Governance cycle
makerdao/governance-manual pull request #42
Opened 2021-12-21 22:01 UTC by mkrorbrkr

@Gala-G @prose11 @blimpa @LongForWisdom 

Added docs for monthly governance cycle and weekly governance cycle

2021-12-22 03:42 UTC, blimpa requested changes
Apologies if too nit-picky.

2021-12-22 03:42 UTC, blimpa commented on governance/monthly-governance-cycle.md
> +- The Governance Facilitators must come to consensus on whether each submission warrants moving forward to a Ratification Poll.
I understand what "each" is trying to do here, but I think "on whether submissions warrant" is the same as "on whether each submission warrants", i.e., "on whether all submissions warrant". I think we should reword this.

2021-12-22 03:42 UTC, blimpa commented on governance/monthly-governance-cycle.md
> +    - Governance Facilitators may consider blocking a proposal if they believe that moving forward to a Ratification Poll would negatively affect community cohesion.
Up to this point we've been using the article before "Governance Facilitators". I like it better without it, tbh.

2021-12-22 03:42 UTC, blimpa commented on governance/monthly-governance-cycle.md
> +-   Ratification Polls are published to the [community GitHub](https://github.com/makerdao/community/tree/master/governance/polls), submitted on-chain and appear on the official [voting portal](https
Maybe mention here that they will run for two weeks?

2021-12-22 03:42 UTC, blimpa commented on governance/weekly-governance-cycle.md
> +The Weekly Governance Cycle is formalized by [MIP16](https://mips.makerdao.com/mips/details/MIP16) and provides predictable weekly framework for Maker Governance decisions.
"provides **a** predictable"

2021-12-22 03:42 UTC, blimpa commented on governance/weekly-governance-cycle.md
> +It complements the Monthly Governance Cycle ([MIP51](https://mips.makerdao.com/mips/details/MIP51)) by enabling recurring weekly decisions to be made that require quicker action.
I feel like there's some subtle incoherence here? Maybe "complements" carries some connotation that makes it sounds as if the Weekly Cycle is an afterthought in spite of its being used for _recurring decisions that require quick action_? Maybe it's just me. But anyway:

I like the wording that we used for the Monthly Gov Cycle better: "The Monthly Governance Cycle _[note the repetition]_ is predominantly used for the introduction of new MIPs or MIP sub-proposals into the Maker Protocol".

I suggest: "The Weekly Governance Cycle is predominantly used for making recurring weekly _[delete?]_ decisions [...]".

2021-12-22 03:42 UTC, blimpa commented on governance/weekly-governance-cycle.md
> +- A **Non-Standard Weekly Poll** is a non-binding weekly poll that has arbitrary time-sensitive decisions. These polls need to be expedited through the Maker governance process via a separate vote. T
"Has arbitrary time-sensitive decisions" is kind of unclear, I think.

"The use of non-standard weekly polls is ~dedicated~ exclusive to Facilitators".

"An example of such a ~poll~ situation".

"due to an abrupt change in market conditions, such as when a vulnerability has been detected". These are two different situations, right? "[...] market conditions, or a vulnerability has been detected" would be better, I think. (But then the examples are kind of unbalanced).

2021-12-22 03:42 UTC, blimpa commented on governance/weekly-governance-cycle.md
> +- Facilitators that have been onboarded into [MIP38: DAO Primitives State](https://github.com/makerdao/mips/blob/master/MIP38/mip38.md) are authorized by Maker Governance to efficiently interact with
"Ratified Facilitators (a list can be found at...)", maybe?

"to ~efficiently~ interact with the weekly cycle to ~enable them to~ fulfill their Core Unit Mandate"? I think we can get rid of this line though, given what follows.

"If necessary, and if it is related to their Core Unit Mandate, Facilitators can skip the **n**on-**s**tandard Weekly poll and include logic directly into the weekly Executive Vote". (If it is necessary but not related to their Core Unit Mandate, they cannot?)

2021-12-22 03:42 UTC, blimpa commented on governance/weekly-governance-cycle.md
> +    - If there are no substantive changes to be made to the Maker Protocol the Governance Facilitators may choose to skip the weekly Executive Vote.
Maybe "Governance Facilitators may choose to skip the weekly Executive Vote if it doesn't introduce substantive or pressing changes to the Maker Protocol"?

2021-12-22 22:01 UTC, mkrorbrkr commented on governance/monthly-governance-cycle.md
> +The Monthly Governance Cycle is predominantly used for the introduction of new MIPs or MIP sub-proposals into the Maker Protocol. Examples of such changes could include:
fixed

2021-12-22 22:02 UTC, mkrorbrkr commented on governance/monthly-governance-cycle.md
> +### Week 1
fixed

2021-12-22 22:03 UTC, mkrorbrkr commented on governance/monthly-governance-cycle.md
> +
Good catch, added

2021-12-22 22:04 UTC, mkrorbrkr commented on governance/monthly-governance-cycle.md
> +-   MIP Editors must be informed by MIP Authors of the status change via commonly used communications channels.
That's the way the MIP is worded so I meant with that. Probably preferable to be descriptive if possible, do you have a suggestion for alternative phrasing?

2021-12-22 22:05 UTC, mkrorbrkr commented on governance/monthly-governance-cycle.md
> +-  Governance Facilitators perform the **Submission Review** as part of the weekly Governance and Risk meeting and communicate which of the proposed MIPs are in accordance with guidelines (defined in
fixed both

2021-12-22 22:06 UTC, mkrorbrkr commented on governance/monthly-governance-cycle.md
> +    - In the event the Governance Facilitators abuse this power **they should be removed from their positions via any method Maker Governance determines is appropriate**.
agreed, added.

2021-12-22 22:07 UTC, mkrorbrkr commented on governance/monthly-governance-cycle.md
> +- The Governance Facilitators must come to consensus on whether each submission warrants moving forward to a Ratification Poll.
I see what you mean. How do you feel about "Must come to a consensus on whether proposed MIPs warrant moving forwards to a Ratification Poll"?

2021-12-22 22:10 UTC, mkrorbrkr commented on governance/monthly-governance-cycle.md
> +    - Governance Facilitators may consider blocking a proposal if they believe that moving forward to a Ratification Poll would negatively affect community cohesion.
So in this instance, I think there is a distinction between "The Governance Facilitators coming to consensus" which suggests both Facilitators reach an agreement, and "Governance Facilitators may consider blocking a proposal" which suggests a single Governance Facilitator has the power to block a proposal independently of the other Governance Facilitator. 

Practically, I'm not sure how this would work though. @prose11 @LongForWisdom may have thoughts on the wording here - could Payton block a proposal unilaterally that Long approves?

2021-12-22 22:11 UTC, mkrorbrkr commented on governance/monthly-governance-cycle.md
> +-   Ratification Polls are published to the [community GitHub](https://github.com/makerdao/community/tree/master/governance/polls), submitted on-chain and appear on the official [voting portal](https
added

2021-12-22 22:11 UTC, mkrorbrkr commented on governance/weekly-governance-cycle.md
> +The Weekly Governance Cycle is formalized by [MIP16](https://mips.makerdao.com/mips/details/MIP16) and provides predictable weekly framework for Maker Governance decisions.
fixed

2021-12-22 22:13 UTC, mkrorbrkr commented on governance/weekly-governance-cycle.md
> +It complements the Monthly Governance Cycle ([MIP51](https://mips.makerdao.com/mips/details/MIP51)) by enabling recurring weekly decisions to be made that require quicker action.
This is the wording used in MIP16 itself, I see your point though, changed for now.

2021-12-22 22:15 UTC, mkrorbrkr commented on governance/weekly-governance-cycle.md
> +- A **Non-Standard Weekly Poll** is a non-binding weekly poll that has arbitrary time-sensitive decisions. These polls need to be expedited through the Maker governance process via a separate vote. T
The first two points are the wording from the MIP. I've changed the second one though because I agree exclusive is better.

I meant a change in market conditions as a result of a vulnerability in that example, but I agree it could be worded better, I've changed it.

2021-12-22 22:20 UTC, mkrorbrkr commented on governance/weekly-governance-cycle.md
> +- Facilitators that have been onboarded into [MIP38: DAO Primitives State](https://github.com/makerdao/mips/blob/master/MIP38/mip38.md) are authorized by Maker Governance to efficiently interact with
Agree with the first two points, changed.

"If necessary, and if it is related to their Core Unit Mandate, Facilitators can skip the non-standard Weekly poll and include logic directly into the weekly Executive Vote" is the wording from the MIP 🤷

2021-12-22 22:20 UTC, mkrorbrkr commented on governance/weekly-governance-cycle.md
> +    - If there are no substantive changes to be made to the Maker Protocol the Governance Facilitators may choose to skip the weekly Executive Vote.
Yeah this is better, changed

2021-12-22 22:21 UTC, mkrorbrkr commented
Thanks for the review @blimpa - no need to apologise, the more pedantic, the better!

2022-01-04 12:01 UTC, Gala-G commented on governance/monthly-governance-cycle.md
> +- The Governance Facilitators must come to consensus on whether each submission warrants moving forward to a Ratification Poll.
Can we go with something like this: 
- The Governance Facilitators must come to consensus on whether each submission meets the guidelines. ?

2022-01-04 12:09 UTC, Gala-G commented on governance/monthly-governance-cycle.md
> +- The Governance Facilitators must come to consensus on whether each submission warrants moving forward to a Ratification Poll.
What about: - The Governance Facilitators must come to consensus on whether each submission SHOULD BE moving forward to a Ratification Poll. ?

2022-01-04 12:16 UTC, Gala-G commented on governance/weekly-governance-cycle.md
> +It works in conjunction with the Monthly Governance Cycle ([MIP51](https://mips.makerdao.com/mips/details/MIP51)) by enabling recurring decisions to be made that require quicker action than is allowe
I suggest we split this sentence to make it clearer:
It works in conjunction with the Monthly Governance Cycle ([MIP51](https://mips.makerdao.com/mips/details/MIP51)). It enables to make recurring operational decisions that require quicker action than what the Monthly Governance Cycle allows.

2022-01-04 12:19 UTC, Gala-G commented on governance/weekly-governance-cycle.md
> +- A **Non-Standard Weekly Poll** is a non-binding weekly poll that has arbitrary time-sensitive decisions. These polls need to be expedited through the Maker governance process via a separate vote. T
For consistence, capitalize Weekly Governance Cycle.

2022-01-04 12:22 UTC, Gala-G commented on governance/weekly-governance-cycle.md
> +- A **Non-Standard Weekly Poll** is a non-binding weekly poll that has arbitrary time-sensitive decisions. These polls need to be expedited through the Maker governance process via a separate vote. T
Add "that": Or a vulnerability THAT has been detected.

2022-01-04 20:45 UTC, mkrorbrkr commented on governance/monthly-governance-cycle.md
> +-   MIP Editors must be informed by MIP Authors of the status change via commonly used communications channels.
@blimpa I changed it to "MIP Authors should inform MIP Editors of the status change via commonly used communications channels." - will go with this unless you have any objections

2022-01-04 21:00 UTC, merged