Patrick j govalpa patch 1
makerdao/governance-manual pull request #58
Opened 2022-01-25 20:12 UTC by patrick-j-govalpha

@LongForWisdom @Gala-G I've started a consistency pass.

I've started with surplus auction parameters. I'll keep moving through different parameters. Let me know if you spot anything else that should be fixed.

2022-01-25 20:35 UTC, patrick-j-govalpha commented
I've now gone through the debt auction docs too

2022-01-26 03:47 UTC, Gala-G commented on governance/weekly-governance-cycle.md
> +- Ratified Facilitators (a list can be found [here](https://mips.makerdao.com/mips/details/MIP38#MIP38c2)) are authorized by Maker Governance to interact with the Weekly Cycle. Facilitators may submi
missing e: Mandate

2022-01-26 03:51 UTC, Gala-G commented on parameter-index/surplus-auction/param-bid-duration-flap.md
> +A larger Bid Duration (Flap) gives keepers more time to participate in auctions, hopefully encouraging a higher number of bidders. If the `Bid Duration (Flap)` is too large, there may be bids for min
there is still one `Bid Duration (Flap)` left - second sentence after "If the..."

2022-01-26 03:54 UTC, Gala-G requested changes

2022-01-26 03:54 UTC, Gala-G commented on parameter-index/debt-auction/param-bid-duration-flop.md
> +A larger Bid Duration (Flop) gives keepers more time to participate in auctions, hopefully encouraging a higher number of bidders. If the Bid Duration (Flop) is too large, there may be bids for very
There is still one `Bid Duration (Flop)` at the end of the second sentence.

2022-01-26 03:56 UTC, Gala-G requested changes

2022-01-26 03:56 UTC, Gala-G commented on governance/weekly-governance-cycle.md
> +- Ratified Facilitators (a list can be found [here](https://mips.makerdao.com/mips/details/MIP38#MIP38c2)) are authorized by Maker Governance to interact with the Weekly Cycle. Facilitators may submi
missing e: Mandate

2022-01-26 03:58 UTC, Gala-G requested changes

2022-01-26 03:58 UTC, Gala-G commented on parameter-index/debt-auction/param-auction-duration-flop.md
> +The the auction will only last 30 minutes, making the Bid Duration (Flop) irrelevant.
Did you mean "Then the auction" ? Erase repetition "The the"

2022-01-26 04:02 UTC, Gala-G commented
Hey Patrick,

They seem pretty good to my non-technical eye. I spotted some typos and addressed them in my review. 
Let's wait for @LongForWisdom to review it and merge it.

thanks!
g

2022-01-26 21:21 UTC, patrick-j-govalpha commented on parameter-index/debt-auction/param-bid-duration-flop.md
> +A larger Bid Duration (Flop) gives keepers more time to participate in auctions, hopefully encouraging a higher number of bidders. If the Bid Duration (Flop) is too large, there may be bids for very
fixed

2022-01-26 21:22 UTC, patrick-j-govalpha commented on parameter-index/surplus-auction/param-bid-duration-flap.md
> +A larger Bid Duration (Flap) gives keepers more time to participate in auctions, hopefully encouraging a higher number of bidders. If the `Bid Duration (Flap)` is too large, there may be bids for min
fixed

2022-01-26 21:23 UTC, patrick-j-govalpha commented on governance/weekly-governance-cycle.md
> +- Ratified Facilitators (a list can be found [here](https://mips.makerdao.com/mips/details/MIP38#MIP38c2)) are authorized by Maker Governance to interact with the Weekly Cycle. Facilitators may submi
fixed

2022-01-26 21:24 UTC, patrick-j-govalpha commented
updated with feedback from @Gala-G

2022-01-30 22:22 UTC, merged