Gala feedback
makerdao/governance-manual pull request #80
Opened 2022-03-07 09:22 UTC by astronautthis

@patrick-j-govalpha

2022-03-10 11:48 UTC, patrick-j-govalpha requested changes
Mostly fine, for some reason I can't comment on it but you need to add double spacing to the end of lines for the sections at the start in blockquote so that the entries appear on separate lines

2022-03-10 11:48 UTC, patrick-j-govalpha commented on module-index/module-lerp.md
> +The `lerp` contract has one method called tick(), which is permissionless and can be called by anyone. This updates the target parameter to be whatever value it should be at that moment. This will al
I'd maybe rephrase the final sentence here - "If the elapsed time is longer than the duration, calling tick() will finish the lerp and set the parameter to the end value."

Presumably it will also change the done parameter - I'm not sure what to, is it "true" if lerp has ended?

2022-03-10 11:48 UTC, patrick-j-govalpha commented on module-index/module-lerp.md
> +When `lerp` is used to determine allocation of protocol earnings, such as setting the surplus buffer, Governance should ensure that the desired rate of increase is not larger than the expected protoc
Capitals for System Surplus Buffer

2022-03-11 11:04 UTC, astronautthis commented on module-index/module-lerp.md
> +The `lerp` contract has one method called tick(), which is permissionless and can be called by anyone. This updates the target parameter to be whatever value it should be at that moment. This will al
Yes, sets done to true - Line 77 of https://github.com/makerdao/dss-lerp/blob/master/src/Lerp.sol

2022-03-11 11:07 UTC, patrick-j-govalpha commented
I think maybe I wasn't clear about the end of line stuff.  You need to add 2 spaces to the end of line 4, 5, and 6 so that the formatting works properly. Look at the rich diff and you can see what I mean

2022-03-11 11:11 UTC, astronautthis commented
> I think maybe I wasn't clear about the end of line stuff. You need to add 2 spaces to the end of line 4, 5, and 6 so that the formatting works properly. Look at the rich diff and you can see what I mean
Gotcha, thanks!

2022-03-11 11:28 UTC, patrick-j-govalpha commented
It still looks weird- did you add extra blank lines? Just needs two spaces "  " at the end of each line

2022-03-12 10:46 UTC, astronautthis commented
> 

Right, sorry I realized now how that works in markdown. Let me know if it's okay now - the only thing missing is the Technical Docs link for it (I don't think there are any other than the GitHub repo itself)

2022-03-20 21:12 UTC, Gala-G commented
@astronautthis  - do you think you can  try resolving the conflicts? I cannot merge it like this. 

Thank you!

2022-03-21 11:12 UTC, astronautthis commented
@Gala-G should be mergeable now. Thanks!

2022-03-21 17:59 UTC, merged