Debt auction bid size
makerdao/governance-manual pull request #89
Opened 2022-04-04 08:07 UTC by astronautthis

@Gala-G

2022-04-16 18:09 UTC, Gala-G commented
@patrick-j-govalpha 

Could you please review this doc before I merge it?
It looks good to me, from a non-technical eye.

thank you so much
g

2022-04-19 16:54 UTC, patrick-j-govalpha requested changes
Content looks fine. A couple of formatting issues to sort out

2022-04-19 16:54 UTC, patrick-j-govalpha commented on parameter-index/debt-auction/param-bid-size.md
> +```
Don't need the "```"

2022-04-19 16:54 UTC, patrick-j-govalpha commented on parameter-index/debt-auction/param-bid-size.md
> +```
Don't need the "```"

2022-04-19 16:54 UTC, patrick-j-govalpha commented on parameter-index/debt-auction/param-bid-size.md
> +---
Don't need this

2022-04-25 13:38 UTC, astronautthis commented
> @patrick-j-govalpha
> 
> Could you please review this doc before I merge it? It looks good to me, from a non-technical eye.
> 
> thank you so much g

Thanks Gala! I've fixed the formatting issues @patrick-j-govalpha pointed out

2022-05-20 19:30 UTC, merged